### ISSUE TITLE
UI Design for GwScan

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#1]
- [x] Home Page: https://www.gwscan.com/
- [x] Block List: https://www.gwscan.com/blocks
- [x] Transaction List: https://www.gwscan.com/txs
- [x] Block Detail: https://www.gwscan.com/block/0x69a1838b1030a505823fb3a6f623a5839d16b9ab52c37cff4c1835222123035d
- [x] Transaction Detail: https://www.gwscan.com/tx/0x8a06ffecf0a3662aa0af9cdbb29e3529f0509f887067e6bdece560fcb74f9960
- [x] User Account Detail: https://www.gwscan.com/account/0x98d6fc98b3c26b9dd3b7e4bac3e11ceb3e7171da
- [x] Contract Account Detail: https://www.gwscan.com/account/0x297ce8d1532704f7be447bc897ab63563d60f223
- [x] Token List: https://www.gwscan.com/tokens/bridge
- [x] Token Detail: https://www.gwscan.com/token/249
- [x] Registered Contract List: https://www.gwscan.com/contracts
- [x] Registered Contract Detail: https://www.gwscan.com/account/0xd66eb642ee33837531fda61eb7ab15b15658bcab
- [x] Charts https://www.gwscan.com/charts

**Comment by Kirl70** [comment]
设计稿链接：https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=0%3A1

mobile端将在web端完成后设计

**Comment by Keith-CY** [comment]
@Magickbase/developers please go through the design draft and add comments in the figma if anything is unclear or needs change.

We will end the first draft review on 6/1

**Comment by Kirl70** [comment]
[首页头部动图.zip](https://github.com/Magickbase/visual-style-guide/files/8841301/default.zip)
首页头部动图mp4文件
