### ISSUE TITLE
Add `size`, `max size of current epoch`, `max size on the chain`, `cycles`, `max cycles of current epoch`, `max cycles on the chain` on transaction and block pages

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#11]
`size` and `cycles` are data to measure performance on CKB.
`size` is the byte count of a transaction or a block
`cycles` could be regarded as `gas used` of a transaction or a block on Ethereum

In this issue, we're going to add 3 types of `size` and 3 types of `cycles` on the block/transaction page.

Where:
1. `size/cycles` of current transaction/block
2. `max size/cycles of current epoch` of current transaction/block, `epoch` is a time span on CKB, could be treated as a series of continue blocks, like `block 0 ~ block 100`
3. `max size/cycles on the chain`, straightforward enough, the biggest value among all transactions/blocks

On the transaction page, these data should be placed together with `block height` and `transaction fee`
![image](https://user-images.githubusercontent.com/7271329/198555416-546ea792-7649-4db3-b13a-f22e1e5b5712.png)

On the block page, these data should be placed together with `block height`, `transactions` ... `uncle count`

![image](https://user-images.githubusercontent.com/7271329/198555691-495aeb6f-475a-43a6-b88b-2a4a81236b71.png)

How:
These data should be displayed in pure numbers, and a progress bar with a tooltip to show percentages as

```
|- transaction/block 10% -|-- max in epoch 30% --|------- max on chain 100% -------|
```

Refs:
size of a blockchain on etherscan: https://etherscan.io/block/15845625
feature request issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/87

**Comment by Kirl70** [comment]
I'm not quite sure of the requirements, here is the preliminary design, please check

<img width="757" alt="image" src="https://user-images.githubusercontent.com/106060898/198867862-54ab9936-f30a-4298-a806-fcf49fd18071.png">

**Comment by Keith-CY** [comment]
> I'm not quite sure of the requirements, here is the preliminary design, please check
> 
> <img alt="image" width="757" src="https://user-images.githubusercontent.com/106060898/198867862-54ab9936-f30a-4298-a806-fcf49fd18071.png">

`cycles` could be thought of as `gas` in ethereum, namely some cost of a transaction.

`cycles of the current transaction` means how much this transaction costs
`max cycles of current epoch` means how much the most expensive transaction in current epoch(e.g. the past 100 transactions) costs
`max cycles on the chain` means how much the most expensive transaction on the chain costs.

`cycles <= max cycles of current epoch <= max cycles on the chain` 

Say `cycles: 10, max cycles of current epoch: 30, max cycles on the chain: 100`, the progress would be

```
transaction   epoch(30-10)        chain cycles(100 - 20 - 10)
|-- 10% --|---- 20% ----|-------------- 70% --------------|
```

**Comment by Kirl70** [comment]
Design Draft: 

<img width="820" alt="image" src="https://user-images.githubusercontent.com/106060898/199207016-54f1263a-3b31-413f-80ef-f6c983cc459c.png">


https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6112%3A27234

**Comment by Keith-CY** [comment]
Hi @Kirl70 , @Danie0918 is our product manager who joined us recently. And advice was proposed for the comparison style in https://github.com/Magickbase/ckb-explorer-public-issues/issues/87#issuecomment-1413464076, which is clearer than what I've sketched. Please update the design for the new layout, thanks

**Comment by Kirl70** [comment]
> Hi @Kirl70 , @Danie0918 is our product manager who joined us recently. And advice was proposed for the comparison style in [Magickbase/ckb-explorer-public-issues#87 (comment)](https://github.com/Magickbase/ckb-explorer-public-issues/issues/87#issuecomment-1413464076), which is clearer than what I've sketched. Please update the design for the new layout, thanks

Draft design has been updated:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6112%3A27234&t=4G8iuyL2OiYsGwgK-1
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/106060898/216557973-6707c27c-b8d1-41a2-9f45-0b382d78741f.png">
