### ISSUE TITLE
Show fee rate on transaction page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#12]
Once `size` is present on the transaction page, `fee rate` could be easily calculated by `fee/size`.

Fee rate could be displayed along with fee, so the row of `fee`
![image](https://user-images.githubusercontent.com/7271329/198562839-87fe6985-1062-40e7-98ca-5592baf7ee33.png)

could be 
```
Transaction Fee | Fee Rate                    0.00001455 CKB | 1000 shannon
```

Ref:
https://github.com/Magickbase/ckb-explorer-public-issues/issues/87#issuecomment-1293170524

**Comment by Kirl70** [comment]
Design Draft:

<img width="593" alt="image" src="https://user-images.githubusercontent.com/106060898/199142238-446880e1-48e0-49a3-90d1-d88c3d7dfbe0.png">

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6102%3A26855
