### ISSUE TITLE
Add a search result page of token in gwscan

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#13]
PRD is described in https://github.com/Magickbase/godwoken_explorer/issues/1159#issuecomment-1316327552

![image](https://user-images.githubusercontent.com/7271329/202084970-87bd87c4-e766-44d2-a9ed-6812e522d782.png)

**Comment by Kirl70** [comment]
Design Draft:

PC
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6325%3A31363&t=KEiGQyBKZmr9tiOo-1

<img width="981" alt="image" src="https://user-images.githubusercontent.com/106060898/202119557-aea60caa-0cb7-41e8-9858-5dc4b049dc2e.png">

Mobile
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6331%3A31581&t=KEiGQyBKZmr9tiOo-1

<img width="237" alt="image" src="https://user-images.githubusercontent.com/106060898/202119618-25d412f4-2565-4cbf-a9b2-d17288581ed0.png">
