### ISSUE TITLE
Support displaying token price and asset value in usd

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#14]
GwScan is going to show users' assets in `usd`(us dollar) so there's going to have 4 updates.

1. price will be displayed on the token detail page, just below the `Total supply` field: https://v1.gwscan.com/token/111
2. a switch icon could be added in the `balance` column of erc 20 asset list on the account page to switch the displaying format of token balance(`amount` <=> `USD`). The column name turns to `USD` when the displaying format is `usd`: https://v1.gwscan.com/account/0xe7970ba16e4922e332ad8ca3650eed7d52cad4d0?tab=assets
3. add a toggle icon in the ERC 20 Transfer list(value column) on the account page: https://v1.gwscan.com/account/0xe7970ba16e4922e332ad8ca3650eed7d52cad4d0?tab=erc20
4. add a switch icon in the ERC 20 Transfer list(value column) on the token page: https://v1.gwscan.com/token/111

Note 1: `price` will be updated periodically so better to append a `(i)` with the `update at yyyy-MM-dd hh:mm:ss` message
Note 2: not every token has `price` info, so the `price` field could be hidden if the token doesn't have a price

Ref: https://github.com/Magickbase/godwoken_explorer/issues/1130

**Comment by Kirl70** [comment]
For price updates, do I need to show all the updated times, or just the latest price times?

**Comment by Kirl70** [comment]
1,4. Add a price field to the token detail page and add a switch USD icon to the transfer list 

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A1144&t=EIvGxqsEoBX6Oakt-1
<img width="858" alt="image" src="https://user-images.githubusercontent.com/106060898/203891505-cbfc7259-7fe3-4185-9412-7d4e085447b9.png">

2. Add switch USD icon to ERC20 assets list on account page

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6635%3A31626&t=EIvGxqsEoBX6Oakt-1
<img width="763" alt="image" src="https://user-images.githubusercontent.com/106060898/203892482-491dc6fb-11d9-493f-bdd4-fb856b0d6d3f.png">

3. Add switch USD icon to ERC20 transfer list on account page

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=118%3A1685&t=EIvGxqsEoBX6Oakt-1
<img width="912" alt="image" src="https://user-images.githubusercontent.com/106060898/203892731-3db8401b-8375-42e7-b64e-307c546ae422.png">

Note 1. Hovering over a price will bring up the updated date for that price
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6635%3A31744&t=EIvGxqsEoBX6Oakt-1
<img width="899" alt="image" src="https://user-images.githubusercontent.com/106060898/203892935-55d8fa4c-7da2-4572-adc0-328113bacc39.png">

**Comment by Keith-CY** [comment]
There're two tiny issues
1. price on the token info page doesn't have the `updated at` time
2. `update time` on hovering price in the list doesn't tell user about the meaning of time, the text could be more detailed as `price updated at {{time}}`

**Comment by Kirl70** [comment]
> There're two tiny issues
> 
> 1. price on the token info page doesn't have the `updated at` time
> 2. `update time` on hovering price in the list doesn't tell user about the meaning of time, the text could be more detailed as `price updated at {{time}}`

The design draft has been adjusted:

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A1144&t=rcVb3GVFmSOhyYYf-1
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/106060898/205494492-e0d4456b-68b6-4be6-a032-032c635b640a.png">

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6635%3A31744&t=rcVb3GVFmSOhyYYf-1
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/106060898/205494509-a1844b8f-d790-4b5c-8315-7685522c9e7b.png">
