### ISSUE TITLE
Support displaying .bit domain

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#15]
PRD: https://github.com/Magickbase/godwoken_explorer/issues/1170#issue-1464097758

Some reference:
- .bit project: https://did.id/
- .bit icon: ![](https://testnet.bridge.godwoken.io/static/dotbit.ico)
- .bit domain icon: this icon is related to the domain, e.g. dear.bit has its own icon ![](https://identicons.did.id/identicon/dear.bit) https://identicons.did.id/identicon/dear.bit

Personally prefer to use the domain-specific icon on account page but should be decided by the designer

**Comment by Kirl70** [comment]
Displaying the icons of the respective domains on different account pages makes the page more distinctive, so I agree with this opinion.

Design Draft:

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2319%3A17211&t=1nad2Vyl7Nk7rAOd-1
<img width="836" alt="image" src="https://user-images.githubusercontent.com/106060898/205252544-81f11c04-8f08-491b-8066-a0e65fd21356.png">
