### ISSUE TITLE
Support displaying .bit domain on CKB Explorer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#16]
Similar to https://github.com/Magickbase/visual-style-guide/issues/15, CKB Explorer is also expected to support .bit domain.

The changes are also similar:
1. Every address text, except the title on `address` page, will be replaced by .bit domain if it has one.
2. If an address has a .bit domain, the domain will be displayed along with the title of the address page(`https://explorer.nervos.org/address/{address}`)

Ref:
https://github.com/Magickbase/ckb-explorer-public-issues/issues/8

**Comment by Kirl70** [comment]
Design Draft:

PC
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5679%3A26337&t=slLEI1I2G0TOskW5-1
<img width="951" alt="image" src="https://user-images.githubusercontent.com/106060898/209496279-9485e4fe-8a90-4762-8a80-cebfe21266eb.png">


Mobile
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5763%3A25290&t=slLEI1I2G0TOskW5-1
<img width="481" alt="image" src="https://user-images.githubusercontent.com/106060898/209100725-37e44838-df2f-4a93-adbb-63803cbaefb2.png">
<img width="304" alt="image" src="https://user-images.githubusercontent.com/106060898/209496312-d3ba2af4-1d0d-4c0f-8eb3-6b736f421d53.png">

**Comment by WhiteMinds** [comment]
@Kirl70 The `transaction hash` is fixed display as `.bit Name` when hover, and the `addresses in the input / output` display the detailed address when hover.

I need to confirm that the two behaviors are different, do I understand this?

**Comment by Kirl70** [comment]
> @Kirl70 The `transaction hash` is fixed display as `.bit Name` when hover, and the `addresses in the input / output` display the detailed address when hover.
> 
> I need to confirm that the two behaviors are different, do I understand this?

Mouse hover over the bit icon to fix the display of `.bit Name`, which is used to tell the user the meaning of this icon. Hovering over the address displays the full address.

**Comment by WhiteMinds** [comment]
> Mouse hover over the bit icon to fix the display of `.bit Name`, which is used to tell the user the meaning of this icon. Hovering over the address displays the full address.

Oh, I got it.
