### ISSUE TITLE
Add a page of transaction fee statistics and estimation

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#18]
PRD(https://github.com/Magickbase/ckb-explorer-public-issues/issues/131) has been confirmed by developers

**Comment by Kirl70** [comment]
Design Draft:
PC
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9729%3A32463&t=AjL1Y5Qolwfi2DnJ-1
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/106060898/210499248-4a1b995b-8eef-4802-89ee-329e08fb9c7d.png">

Mobile
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9729%3A32197&t=AjL1Y5Qolwfi2DnJ-1
<img width="206" alt="image" src="https://user-images.githubusercontent.com/106060898/210499329-b728bbf1-b362-4e52-b3bd-e94cc31f858e.png">

**Comment by Keith-CY** [comment]
@WhiteMinds @pygman please have a review
