### ISSUE TITLE
Add a pie chart of miner version distribution on https://explorer.nervos.org/charts

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#19]
PRD(https://github.com/Magickbase/ckb-explorer-public-issues/issues/137) has been confirmed by developers

**Comment by Kirl70** [comment]
Design Draft:
PC
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9739%3A32722&t=OjTMMhLRbeO59G8y-1
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/106060898/210499014-f3344ff0-aa07-4eb7-acff-57b6a5dbf393.png">

Mobile
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9739%3A32766&t=OjTMMhLRbeO59G8y-1
<img width="361" alt="image" src="https://user-images.githubusercontent.com/106060898/210499125-3276a71c-f60d-45ca-9d54-343212a7754c.png">

**Comment by Keith-CY** [comment]
Looks good to me, any idea from @WhiteMinds @pygman

**Comment by WhiteMinds** [comment]
I don't know if this custom tooltip on the chart is easy to implement, but I need to look at the echarts api and learn more about it when it is actually implemented.
#18 have the same problem.

**Comment by Keith-CY** [comment]
> I don't know if this custom tooltip on the chart is easy to implement, but I need to look at the echarts api and learn more about it when it is actually implemented. #18 have the same problem.

Good point, I've checked the current style used in other charts 

![image](https://user-images.githubusercontent.com/7271329/210480488-462cf87c-4e1a-401a-84e4-b3b5972774f5.png)

Maybe we should keep them consistent @Kirl70

**Comment by Kirl70** [comment]
> > I don't know if this custom tooltip on the chart is easy to implement, but I need to look at the echarts api and learn more about it when it is actually implemented. #18 have the same problem.
> 
> Good point, I've checked the current style used in other charts
> 
> ![image](https://user-images.githubusercontent.com/7271329/210480488-462cf87c-4e1a-401a-84e4-b3b5972774f5.png)
> 
> Maybe we should keep them consistent @Kirl70

Draft design has been updated
