### ISSUE TITLE
UI Design for Neuron

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#2]

**Comment by Keith-CY** [comment]
# Landing page

![image](https://user-images.githubusercontent.com/7271329/171394237-5fdcb99c-2cde-4d28-9b71-2a6532c054ec.png)

**Comment by Keith-CY** [comment]
## Create a wallet

![image](https://user-images.githubusercontent.com/7271329/171394342-830b5a1d-8e11-47de-8925-cfa33e52c1fc.png)
![image](https://user-images.githubusercontent.com/7271329/171394360-19e71e66-0b40-4281-9de6-8f3004a9021e.png)
![image](https://user-images.githubusercontent.com/7271329/171394425-5c5d41cf-edbc-4260-8166-359661a04744.png)
![image](https://user-images.githubusercontent.com/7271329/171394478-fca29aaa-f597-416c-a967-f137ab85771f.png)

**Comment by Keith-CY** [comment]
## Import keystore
![image](https://user-images.githubusercontent.com/7271329/171394726-0841a3ce-31c9-4160-a5d7-7fd0a9aa8463.png)

**Comment by Keith-CY** [comment]
## Overview
![image](https://user-images.githubusercontent.com/7271329/171395068-1823f6b0-1213-4134-ac96-8e744e172e43.png)

**Comment by Keith-CY** [comment]
## Send

Single reeciver
![image](https://user-images.githubusercontent.com/7271329/171395179-1b4f40ee-5bc8-414b-a169-00376b83e22f.png)

Multiple receivers
![image](https://user-images.githubusercontent.com/7271329/171395269-51d18fc1-2d30-41e9-bd65-c695ed839dea.png)

Custom Fee
![image](https://user-images.githubusercontent.com/7271329/171395411-f21f79f0-a624-4203-8b59-6c520a33b1a0.png)

**Comment by Keith-CY** [comment]
## Receive Address
![image](https://user-images.githubusercontent.com/7271329/171395535-83964b97-6d0a-409d-bed4-8424be71fc86.png)

Address book
![image](https://user-images.githubusercontent.com/7271329/171395570-dcd04ad7-dbd6-4aac-88fc-0d1f838ff591.png)

**Comment by Keith-CY** [comment]
## Transaction history

![image](https://user-images.githubusercontent.com/7271329/171395663-12640b31-d9e7-4a9a-a3b9-b89d846c4ed0.png)

Detail
![image](https://user-images.githubusercontent.com/7271329/171395694-dad3b948-f3a2-4fc4-b1a8-9d1be43fe2d6.png)
![image](https://user-images.githubusercontent.com/7271329/171395724-806361cf-be4d-41b5-abd1-472b610848f1.png)

**Comment by Keith-CY** [comment]
## Nervos DAO

deposit
![image](https://user-images.githubusercontent.com/7271329/171395888-b6fa26fa-72da-445e-bdb6-a3acf4ce3580.png)

deposited record
![image](https://user-images.githubusercontent.com/7271329/171395963-ecb87f5a-bdda-4c37-8e42-572ed27b3f9e.png)

unlocked record(waiting for withdrawing)
![image](https://user-images.githubusercontent.com/7271329/171396022-5ecc7bc3-fe14-499d-9f0b-578ccc6d76ce.png)

finished record
![image](https://user-images.githubusercontent.com/7271329/171396549-59b918f5-b74f-4d95-b124-67783daf888c.png)

**Comment by Keith-CY** [comment]
## Nervos DAO

deposit
![image](https://user-images.githubusercontent.com/7271329/171395888-b6fa26fa-72da-445e-bdb6-a3acf4ce3580.png)

deposited record
![image](https://user-images.githubusercontent.com/7271329/171395963-ecb87f5a-bdda-4c37-8e42-572ed27b3f9e.png)

unlocked record(waiting for withdrawing)
![image](https://user-images.githubusercontent.com/7271329/171396022-5ecc7bc3-fe14-499d-9f0b-578ccc6d76ce.png)

finished record
![image](https://user-images.githubusercontent.com/7271329/171396549-59b918f5-b74f-4d95-b124-67783daf888c.png)

**Comment by Keith-CY** [comment]
## Custom Assets
![image](https://user-images.githubusercontent.com/7271329/171397454-dcd70000-6ccd-4a47-86d5-86f3f5e39879.png)

send nft
![image](https://user-images.githubusercontent.com/7271329/171396920-1ea57c35-e079-4233-a9a8-93dd75cd5793.png)

migrate sudt asset
![image](https://user-images.githubusercontent.com/7271329/171397023-34597aa4-bda1-418e-9ae2-b6c02fe5d7af.png)
migrate sudt asset to a new sudt asset accout
![image](https://user-images.githubusercontent.com/7271329/171397036-3892f960-0385-402b-b709-f35ae7a740c4.png)
transfer to a sudt asset account
![image](https://user-images.githubusercontent.com/7271329/171397113-e86c3a03-9082-4e97-8268-d4058012ba01.png)

**Comment by Keith-CY** [comment]
## Asset account

![image](https://user-images.githubusercontent.com/7271329/171397600-70a0c3ab-cfd1-45ed-aaca-6efba7209379.png)
![image](https://user-images.githubusercontent.com/7271329/171397626-62c99789-54b5-44e8-bba9-1be858fff689.png)

add sudt account
![image](https://user-images.githubusercontent.com/7271329/171397702-776f52ee-b659-46de-9254-290760bb6e0a.png)
![image](https://user-images.githubusercontent.com/7271329/171397731-f02d949b-373b-498b-ae9c-56a9c68bcb29.png)

add ckb account
![image](https://user-images.githubusercontent.com/7271329/171397771-91407e1b-7889-47d4-95c9-e0f7b5a945a2.png)

edit
![image](https://user-images.githubusercontent.com/7271329/171397894-c4605b7f-c9a1-4480-ac43-857e0b11f407.png)

receive address
![image](https://user-images.githubusercontent.com/7271329/171397937-25d048f4-9c0d-405c-9df8-ad944c17fed7.png)

send from ckb account
![image](https://user-images.githubusercontent.com/7271329/171398004-be0e07d1-d721-4d6d-807d-be1d5671a040.png)
![image](https://user-images.githubusercontent.com/7271329/171398042-2e2dfa53-b26f-42eb-9d1d-1f651394dbcc.png)

send from sudt account
![image](https://user-images.githubusercontent.com/7271329/171398112-4ead664a-b8fe-4121-9151-d3f387132102.png)

**Comment by Keith-CY** [comment]
## Setting

general
![image](https://user-images.githubusercontent.com/7271329/171398291-cfe9630d-5966-48f3-8a57-0b5d67251ecc.png)

release note
![image](https://user-images.githubusercontent.com/7271329/171398808-f00faa41-bcb1-4428-9db6-f1203c7139d9.png)

download new version
![image](https://user-images.githubusercontent.com/7271329/171398870-dedba262-bb4a-4db5-91b4-4655d2e90042.png)

clear cache
![image](https://user-images.githubusercontent.com/7271329/171398384-ff9ba4d1-f47f-4601-a860-f39574368982.png)

wallets management
![image](https://user-images.githubusercontent.com/7271329/171398412-38cf0dd5-26a4-4211-800d-0c66a6dae358.png)

network list
![image](https://user-images.githubusercontent.com/7271329/171398456-b8394f69-e654-4166-bc79-21d738fab29e.png)

add or edit network
![image](https://user-images.githubusercontent.com/7271329/171398501-44ddefe2-ef3b-4e64-b4f0-b6b055cfcc40.png)

**Comment by Keith-CY** [comment]
## Sign and verify

![image](https://user-images.githubusercontent.com/7271329/171399015-ac88df25-52b7-48d2-9bb0-e12cbedcccfc.png)

![image](https://user-images.githubusercontent.com/7271329/171399078-7be9da66-1af8-4dcd-b1cb-8df70e05def5.png)

![image](https://user-images.githubusercontent.com/7271329/171399177-2d106bb3-6343-492a-b0a1-595c985f8766.png)

![image](https://user-images.githubusercontent.com/7271329/171399197-408c8f21-3948-490b-8883-313d5201f393.png)

![image](https://user-images.githubusercontent.com/7271329/171399209-a2c032a4-25f2-4910-8e09-ccc44cae38a5.png)

**Comment by Keith-CY** [comment]
## multisig

![image](https://user-images.githubusercontent.com/7271329/171399276-cd50c26a-2704-4cec-8cca-d6d3be9a0fb0.png)
![image](https://user-images.githubusercontent.com/7271329/171399343-7775d9c0-20df-4c84-b8a0-10a8ab9ea962.png)
![image](https://user-images.githubusercontent.com/7271329/171399557-2ae43ba7-eff4-485f-974c-1d4e8f212919.png)
![image](https://user-images.githubusercontent.com/7271329/171399573-fc1591b0-fc36-4c87-a9b1-eef46a95fb07.png)
![image](https://user-images.githubusercontent.com/7271329/171399622-4d51270f-e069-459c-93c7-6a959b1ab953.png)

Send
![image](https://user-images.githubusercontent.com/7271329/171399769-3cd71752-9b0d-482f-9acb-208cbf5912ff.png)

Approve
![image](https://user-images.githubusercontent.com/7271329/171399866-6108cc11-af77-4ff0-81d3-caaba58d5d55.png)
![image](https://user-images.githubusercontent.com/7271329/171400505-5946c93c-cdf1-471a-aa35-4436b26c7d91.png)

![image](https://user-images.githubusercontent.com/7271329/171399889-5b7103f6-200f-4e8a-a408-ef2e5ed20113.png)

**Comment by Keith-CY** [comment]
## Offline sign

![image](https://user-images.githubusercontent.com/7271329/171400608-7308635f-f829-4f73-b86e-6e28a2a7f216.png)

**Comment by Kirl70** [comment]
登录/导入、总览、转账、收款页已上传figma
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=412%3A4693

**Comment by Keith-CY** [comment]
> 登录/导入、总览、转账、收款页已上传figma [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=412%3A4693](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=412%3A4693)

Please have a review @yanguoyu @qiweiii @Cedar67 @sonycs @zmcNotafraid @Naupio @ShiningRay

**Comment by Kirl70** [comment]
交易历史、Nervos DAO 页已上传figma

**Comment by Kirl70** [comment]
设置、自定义资产、资产账户页已上传figma

**Comment by Kirl70** [comment]
签名/验签信息、多签地址、离线签名页面已上传figma，全部页面流程已设计完成；接下来设计夜间模式。 @Keith-CY

**Comment by Kirl70** [comment]
设置增加「数据」选项已更新至设计稿

**Comment by Kirl70** [comment]
夜间模式已更新至设计稿 https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=1387%3A10877

**Comment by Keith-CY** [comment]
Please have a review on the design of Neuron @yanguoyu @qiweiii @Cedar67 @FrederLu

**Comment by Keith-CY** [comment]
Review will end on 07/20

**Comment by Cedar67** [comment]
@Kirl70  Whether it is convenient to create directory for pages list on the left side by category？

![image](https://user-images.githubusercontent.com/64718893/179665548-12bee4ba-d522-4a1a-80a4-142d90f1bb41.png)

**Comment by Kirl70** [comment]
> @Kirl70 左侧页面列表按类别创建目录是否方便？
> 
> ![图片](https://user-images.githubusercontent.com/64718893/179665548-12bee4ba-d522-4a1a-80a4-142d90f1bb41.png)

<img width="239" alt="image" src="https://user-images.githubusercontent.com/106060898/179692861-919f3e67-8702-4605-b1cb-5778b8a5fa95.png">

已按功能创建分类，并将画板按序号重新拍序。注：在列表选中画板名称后按 Shift+2 可快速跳转到对应设计稿页面。

**Comment by Kirl70** [comment]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/106060898/180114692-44569bd4-e2af-4c81-8a05-7f6165dd6904.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/106060898/180114731-c03fd2e0-7c2f-4d77-8250-98fbc8a8ea1e.png">

这两个卡片内的特殊数字字体文件，压缩包里包含otf和ttf两种格式，按需所取
[D-DIN-PRO-500-Medium.zip](https://github.com/Magickbase/visual-style-guide/files/9155621/D-DIN-PRO-500-Medium.zip)

**Comment by Keith-CY** [comment]
Now that UI Design has been reviewed, could you open another issue to track the progress of implementing the UI @yanguoyu, just split the whole one into small tasks and add estimated work time next to each one, then we can arrange them to developers.

**Comment by yanguoyu** [comment]
1. <img width="654" alt="image" src="https://user-images.githubusercontent.com/12881040/180716683-bf0904a1-03e3-4c61-af32-432c708811d6.png">
2. 
<img width="783" alt="image" src="https://user-images.githubusercontent.com/12881040/180716780-3261b50f-c259-4942-89ae-3de78322716a.png">
3. 
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/12881040/180716920-85d73389-6688-4868-bde6-cffb8acfa930.png">
这几个全局提示还需要保留吗？
@Keith-CY

**Comment by Keith-CY** [comment]
1. 是在 nervos dao 中 进行解锁操作之后记录出现的吗
2. 重构数据库是比较早的版本, 在硬分叉之前, 不会再有用户使用了, 这个通知可以去掉
3. 复制二维码有独立的交互通知

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/180717736-d402dccd-30f8-429a-813b-72b3711e2b9d.png)
复制二维码的通知

**Comment by Kirl70** [comment]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/106060898/180722667-70c4777d-fc52-41de-9391-81d0bac0250f.png">

1的弹框可以按图所示，文案不同。@yanguoyu

**Comment by yanguoyu** [comment]
@Kirl70 我看`创建钱包，生成助记词` 页面有用到 `Proxima Nova` 这个字体，好像不是系统自带的。我们是把这个下载下来放进去还是怎么处理？另外我看大部分都是 `PingFang SC` 这个字体，如果是 windows 用户也用 `PingFang SC` 字体吗？普通字体方面可以订一个统一的规则。

**Comment by Kirl70** [comment]
> @Kirl70 我看`创建钱包，生成助记词` 页面有用到 `Proxima Nova` 这个字体，好像不是系统自带的。我们是把这个下载下来放进去还是怎么处理？另外我看大部分都是 `PingFang SC` 这个字体，如果是 windows 用户也用 `PingFang SC` 字体吗？普通字体方面可以订一个统一的规则。

[ProximaNova.zip](https://github.com/Magickbase/visual-style-guide/files/9468368/ProximaNova.zip)

`Proxima Nova`字体已补充，供有该字体的页面使用。 其它页面里普通文字用各自带的系统字体即可。@yanguoyu

**Comment by Cedar67** [comment]
在设计图看到有以下四种字体。其中`PingFang SC`作为普通字体，根据系统字体决定显示方式；其他三种字体采用统一显示方式。 这样理解对吗 @Kirl70 
```
- DINPro
- PingFang SC
- D-DIN-PRO
- Proxima Nova
```

**Comment by Kirl70** [comment]
> 在设计图看到有以下四种字体。其中`PingFang SC`作为普通字体，根据系统字体决定显示方式；其他三种字体采用统一显示方式。 这样理解对吗 @Kirl70
> 
> ```
> - DINPro
> - PingFang SC
> - D-DIN-PRO
> - Proxima Nova
> ```

<img width="388" alt="image" src="https://user-images.githubusercontent.com/106060898/188053473-35b22450-7e38-4ce4-959b-114444c85852.png">

[JetBrainsMonoNL.zip](https://github.com/Magickbase/visual-style-guide/files/9474656/JetBrainsMonoNL.zip)

实际上是有以上4种字体，每个字体又分2种粗细度。之前少了个地址的字体`JetBrainsMonoNL`（与浏览器的地址信息字体一致），现已补充@yanguoyu。

`DINPro` `D-DIN-PRO` 其实是一种字体，因为`DINPro`可能会有版权问题所以已经统一改成 `D-DIN-PRO` （设计稿已调整）。普通字体是根据系统字体显示，Mac系统一般是`PingFang SC`，其它系统就由系统自带字体决定。@Cedar67
