### ISSUE TITLE
Add a GasLess tx page

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/visual-style-guide#20]
https://github.com/Magickbase/godwoken_explorer/issues/1163#issuecomment-1374436759

Design Draft:
PC
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9843%3A32919&t=1f6o4riVmZRgk507-1
<img width="718" alt="image" src="https://user-images.githubusercontent.com/106060898/211574686-b063bc8f-806d-4d38-86c5-4660f1f1ff0f.png">

Mobile
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9843%3A33202&t=1f6o4riVmZRgk507-1
<img width="275" alt="image" src="https://user-images.githubusercontent.com/106060898/211574787-174ad310-db7b-4c1d-9bf0-361f41f33e22.png">

@Keith-CY @qiweiii

**Comment by Keith-CY** [comment]
It's expected to be a single-column section because `call data` would be long and will be parsed in future

A wide zone is better to display the parsed data as
![image](https://user-images.githubusercontent.com/7271329/211190544-d3bbc533-2b09-4049-ac54-ba0b44d6b4d3.png)

**Comment by Kirl70** [comment]
> It's expected to be a single-column section because `call data` would be long and will be parsed in future
> 
> A wide zone is better to display the parsed data as ![image](https://user-images.githubusercontent.com/7271329/211190544-d3bbc533-2b09-4049-ac54-ba0b44d6b4d3.png)

Got it, the draft design has been adjusted

**Comment by qiweiii** [comment]
@Kirl70 I saw the design is still two column
