### ISSUE TITLE
Adjust fee rate selection in Neuron

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#21]
PRD: https://github.com/Magickbase/neuron-public-issues/issues/87#issuecomment-1371219123

The main change is case 1 mentioned in https://github.com/Magickbase/neuron-public-issues/issues/87#issuecomment-1371219123

> For case 1,
> 
> rename `advanced fee settings` to `custom fee rate`
> 
> if `custom fee rate` is unchecked, the fee rate dropdown list is displayed with 3 options
> 
> Fast: fee rate is `2 * suggested_fee_rate - 1000`
> Standard: fee rate is `suggested_fee_rate`
> Slow: fee rate is `1000`
> Each option is displayed with `priority`(fast, standard, slow), `fee rate`, and `fee`. The standard one is selected by default.
> 
> if custom fee rate is checked, a text field is displayed and the dropdown list is hidden. The text field allows the user to input a custom fee rate.
> 
> the suggested fee rate is displayed beneath the text field if it's empty
> the fee is displayed (instead of the suggested fee rate) beneath the text field if it's not empty
> an error message is displayed (instead of the fee/suggested fee rate) if the custom fee rate is invalid(not a number, less than 1000)
> the suggested fee rate is refreshed every 10 blocks

![image](https://user-images.githubusercontent.com/7271329/211969794-db456821-1b51-4778-b697-2b3cf323058d.png)

with a suggestion of `countdown to refresh` mentioned in https://github.com/Magickbase/neuron-public-issues/issues/87#issuecomment-1374785309

I also noticed that the terminology `fee rate` was replaced by `price` for understanding, and it will be used for consistency.

In summary,
1. `advance fee settings` will be renamed to `custom price`
2. if `custom price` is unchecked, the `price` is set by selecting an option of a dropdown list with 3 gears
	1. `fast`
	2. `standard`
	3. `slow`
   `standard` is selected by default
    each option is displayed with 3 fields
    1. `priority`: fast, standard, slow
    2. `price`
    3. `fee`
3. if `custom price` is checked, the `price` is set by a text field instead of selecting from the dropdown list
	1. if the text field is empty, `suggested price` will be displayed beneath the text field
	2. if the text field is filled and data are correct, `fee` will be displayed beneath the text field, and `suggested price` is hidden
	3. if the text field is filled while data are invalid, error message will be displayed beneath the text field, `suggested price` and `fee` are hidden

Please have a review, and any questions could be attached @Kirl70 

If the request is clear enough, please add a UI design for the current UI and update the new UI because the development of new UI is still ongoing.

**Comment by Kirl70** [comment]
Please check the feature flow first, if there is no problem I will update the custom asset section and the new UI @Keith-CY 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/106060898/212592467-336eb124-8670-461d-9f2a-c4ebd083e76e.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/106060898/212592490-824cb160-ce07-4347-b861-48a810a4cba8.png">

<img width="939" alt="image" src="https://user-images.githubusercontent.com/106060898/212592670-ba6b955f-afcc-464a-bcdb-79ef782432cb.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/106060898/212591253-99f0582e-5798-4482-8857-f8215308b717.png">

<img width="857" alt="image" src="https://user-images.githubusercontent.com/106060898/212591267-8c257042-b717-469a-b8e6-2fa2e7e02218.png">

**Comment by Keith-CY** [comment]
> Please check the feature flow first, if there is no problem I will update the custom asset section and the new UI @Keith-CY
> 
> <img alt="image" width="859" src="https://user-images.githubusercontent.com/106060898/212592467-336eb124-8670-461d-9f2a-c4ebd083e76e.png">
> 
> <img alt="image" width="864" src="https://user-images.githubusercontent.com/106060898/212592490-824cb160-ce07-4347-b861-48a810a4cba8.png">
> 
> <img alt="image" width="939" src="https://user-images.githubusercontent.com/106060898/212592670-ba6b955f-afcc-464a-bcdb-79ef782432cb.png">
> 
> <img alt="image" width="856" src="https://user-images.githubusercontent.com/106060898/212591253-99f0582e-5798-4482-8857-f8215308b717.png">
> 
> <img alt="image" width="857" src="https://user-images.githubusercontent.com/106060898/212591267-8c257042-b717-469a-b8e6-2fa2e7e02218.png">

The workflow is correct.

The terminology `fee rate` is too technical, `price` could be used instead(it's used in the released versions)
And `dynamic fee rate/price` is also technical, `price` is good. Namely, the label is `Price` or `Custom Price`

**Comment by Kirl70** [comment]
Design Draft:

Released versions (transfers and asset accounts)
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=10403%3A33904&t=p9VnYrqZV7zxrcMI-1

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/106060898/213351144-daf96f83-90af-40c9-aae6-3e2b35e41cb8.png">

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/106060898/213351236-25b7ed75-1bd1-4c3e-8498-f2b43dcf0e18.png">

New UI (transfers and asset accounts)
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=1864%3A13005&t=CCpAAtf8hmnQNdSf-1

<img width="826" alt="image" src="https://user-images.githubusercontent.com/106060898/213355399-d3dd7d32-cb0c-4abd-a0f0-512bcc3acf85.png">

<img width="875" alt="image" src="https://user-images.githubusercontent.com/106060898/213355476-02683b9a-ba66-483e-b6e1-c107ce46b877.png">
