### ISSUE TITLE
Design a logo for project kuai

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#23]
We're going to promote a project named **kuai** to the community and need an impressive logo for it.

---

Project **kuai**: https://github.com/ckb-js/kuai

### Overview:

**Kuai** is an application development **philosophy** and all-in-one development **framework** designed specifically for Nervos CKB. It encompasses generic application development **patterns**, convenient development **scaffolding**, plug-and-play application **architecture**, and development **manuals** to facilitate development processes.

### Design element from kuai project proposer

**Kuai**, the name of the project, comes from the following meanings
1. speedy: this project facilitates the development of dapp on nervos ckb;
2. chopsticks: 
    1. this project is the best mate for developers on nervos ckb;
    2. developers make life (earn money) by using chopsticks;
3. block: this project is for blockchain development.

### Design style preference of kuai developers

> For me, the text "Kuai", "Magickbase", the symbol of "blockchain", "tool set", "speed" should be included.
> And personally, I prefer a logo of characters on a block, or dice for random possibilities, or a badge for prints.

> I prefer colorful logo

**Comment by Kirl70** [comment]
The following is the LOGO scheme:
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/106060898/236608075-e0ddda5f-68fa-4c82-8329-8e846be31201.png">

**Comment by Daryl-L** [comment]
喜欢第四个

**Comment by yanguoyu** [comment]
I like the first's shadow design, but not like the word `a`'s style.
And the fourth is also good, but I think we can keep the top icon and remove the `kuai` word.

**Comment by Keith-CY** [comment]
Actually, the second one can be interpreted as using chopsticks to manipulate `cells/blocks`, but it also reminds me of the `kitchen`, which may not be so cool as a technical framework.

However, the fashion word `omakase` can be derived from `kitchen`, this word is used to describe `ruby on rails`, which offers the best/opinioned choices to developers so they can focus themselves on business.

Ref:
- Rails is omakase: https://dhh.dk/2012/rails-is-omakase.html

**Comment by Keith-CY** [comment]
The fourth one looks more coordinated, but lacks uniqueness

**Comment by Kirl70** [comment]
Ok, I will make adjustments as suggested

**Comment by Kirl70** [comment]
Adjusted design solution:

<img width="1312" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/c8899714-b476-4813-9f8b-9d865f4430d8">

**Comment by yanguoyu** [comment]
vote 5

**Comment by Kirl70** [comment]
@Keith-CY Please select a suitable logo or adjust the comments.

**Comment by Daryl-L** [comment]
vote 5 too

**Comment by Keith-CY** [comment]
> @Keith-CY Please select a suitable logo or adjust the comments.

I also think logo 5 is more dynamic and impressive, but I cannot associate it with the concept of a development framework or toolkit that speeds up the development of a DApp.

As mentioned at https://github.com/Magickbase/visual-style-guide/issues/23#issue-1688041863

> **Kuai** is an application development **philosophy** and all-in-one development **framework** designed specifically for Nervos CKB. It encompasses generic application development **patterns**, convenient development **scaffolding**, plug-and-play application **architecture**, and development **manuals** to facilitate development processes.

It would be great to tell users that **kuai** is about **abstract philosophy** and **concrete framework/tools** by the logo

**Comment by Kirl70** [comment]
> > @Keith-CY Please select a suitable logo or adjust the comments.
> 
> I also think logo 5 is more dynamic and impressive, but I cannot associate it with the concept of a development framework or toolkit that speeds up the development of a DApp.
> 
> As mentioned at [#23 (comment)](https://github.com/Magickbase/visual-style-guide/issues/23#issue-1688041863)
> 
> > **Kuai** is an application development **philosophy** and all-in-one development **framework** designed specifically for Nervos CKB. It encompasses generic application development **patterns**, convenient development **scaffolding**, plug-and-play application **architecture**, and development **manuals** to facilitate development processes.
> 
> It would be great to tell users that **kuai** is about **abstract philosophy** and **concrete framework/tools** by the logo

ok, I will adjust again

**Comment by Kirl70** [comment]
I think that representing specific frameworks/tools in a graphical form within the logo would make it complex and difficult to identify. Therefore, I have chosen to design the logo around the symbol "<>", which best represents development.
@Keith-CY 

<img width="1131" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/82718906-3b80-4fae-bb23-42984cbb7e8e">

**Comment by Keith-CY** [comment]
> I think that representing specific frameworks/tools in a graphical form within the logo would make it complex and difficult to identify. Therefore, I have chosen to design the logo around the symbol "<>", which best represents development. @Keith-CY
> 
> <img alt="image" width="1131" src="https://user-images.githubusercontent.com/106060898/244246988-82718906-3b80-4fae-bb23-42984cbb7e8e.png">

![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/ff176673-b75c-44cc-b9c2-b10e08b38572)
is impressive to me because it balances abstract(code <>) and concrete(tool box)

![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/5937b22b-31ad-4000-80a4-e1400ab67724)
is a bit similar to another project in CKB ecosystem, [axon web3](https://github.com/axonweb3)


Which one is your favorite among all above, including https://github.com/Magickbase/visual-style-guide/issues/23#issuecomment-1541471512

@Daryl-L @PainterPuppets @yanguoyu @zhengjianhui

**Comment by Keith-CY** [comment]
> > I think that representing specific frameworks/tools in a graphical form within the logo would make it complex and difficult to identify. Therefore, I have chosen to design the logo around the symbol "<>", which best represents development. @Keith-CY
> > <img alt="image" width="1131" src="https://user-images.githubusercontent.com/106060898/244246988-82718906-3b80-4fae-bb23-42984cbb7e8e.png">
> 
> ![image](https://user-images.githubusercontent.com/7271329/244288779-ff176673-b75c-44cc-b9c2-b10e08b38572.png) is impressive to me because it balances abstract(code <>) and concrete(tool box)
> 
> ![image](https://user-images.githubusercontent.com/7271329/244289011-5937b22b-31ad-4000-80a4-e1400ab67724.png) is a bit similar to another project in CKB ecosystem, [axon web3](https://github.com/axonweb3)
> 
> Which one is your favorite among all above, including [#23 (comment)](https://github.com/Magickbase/visual-style-guide/issues/23#issuecomment-1541471512)
> 
> @Daryl-L @PainterPuppets @yanguoyu @zhengjianhui

Which one would you prefer @Daryl-L @PainterPuppets @yanguoyu

**Comment by yanguoyu** [comment]
![image](https://user-images.githubusercontent.com/7271329/244289011-5937b22b-31ad-4000-80a4-e1400ab67724.png)
I would prefer this.

**Comment by Keith-CY** [comment]
> ![image](https://user-images.githubusercontent.com/7271329/244289011-5937b22b-31ad-4000-80a4-e1400ab67724.png) I would prefer this.

It's a bit similar to the axon team's logo at https://github.com/axonweb3
![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/b5281fa0-bcd5-40ab-9a80-3c6040a7fe6a)

**Comment by Daryl-L** [comment]
> > > I think that representing specific frameworks/tools in a graphical form within the logo would make it complex and difficult to identify. Therefore, I have chosen to design the logo around the symbol "<>", which best represents development. @Keith-CY
> > > <img alt="image" width="1131" src="https://user-images.githubusercontent.com/106060898/244246988-82718906-3b80-4fae-bb23-42984cbb7e8e.png">
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/7271329/244288779-ff176673-b75c-44cc-b9c2-b10e08b38572.png) is impressive to me because it balances abstract(code <>) and concrete(tool box)
> > ![image](https://user-images.githubusercontent.com/7271329/244289011-5937b22b-31ad-4000-80a4-e1400ab67724.png) is a bit similar to another project in CKB ecosystem, [axon web3](https://github.com/axonweb3)
> > Which one is your favorite among all above, including [#23 (comment)](https://github.com/Magickbase/visual-style-guide/issues/23#issuecomment-1541471512)
> > @Daryl-L @PainterPuppets @yanguoyu @zhengjianhui
> 
> Which one would you prefer @Daryl-L @PainterPuppets @yanguoyu

I prefer the last one.

**Comment by Keith-CY** [comment]
> > > > I think that representing specific frameworks/tools in a graphical form within the logo would make it complex and difficult to identify. Therefore, I have chosen to design the logo around the symbol "<>", which best represents development. @Keith-CY
> > > > <img alt="image" width="1131" src="https://user-images.githubusercontent.com/106060898/244246988-82718906-3b80-4fae-bb23-42984cbb7e8e.png">
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/7271329/244288779-ff176673-b75c-44cc-b9c2-b10e08b38572.png) is impressive to me because it balances abstract(code <>) and concrete(tool box)
> > > ![image](https://user-images.githubusercontent.com/7271329/244289011-5937b22b-31ad-4000-80a4-e1400ab67724.png) is a bit similar to another project in CKB ecosystem, [axon web3](https://github.com/axonweb3)
> > > Which one is your favorite among all above, including [#23 (comment)](https://github.com/Magickbase/visual-style-guide/issues/23#issuecomment-1541471512)
> > > @Daryl-L @PainterPuppets @yanguoyu @zhengjianhui
> > 
> > 
> > Which one would you prefer @Daryl-L @PainterPuppets @yanguoyu
> 
> I prefer the last one.

Comes out that
![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/0dda5bac-4de0-4dde-b85f-fb5c6f2aa1a3)
![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/a6ec1b2c-03e9-45cb-8fc9-33b05617159f)
![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/99f7a6df-ddb6-4c79-932e-5866cd60969f)
are preferred by each one

Which one in the whole list(not only 3 above) do you pick @PainterPuppets

**Comment by PainterPuppets** [comment]
> > > > > I think that representing specific frameworks/tools in a graphical form within the logo would make it complex and difficult to identify. Therefore, I have chosen to design the logo around the symbol "<>", which best represents development. @Keith-CY
> > > > > <img alt="image" width="1131" src="https://user-images.githubusercontent.com/106060898/244246988-82718906-3b80-4fae-bb23-42984cbb7e8e.png">
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/7271329/244288779-ff176673-b75c-44cc-b9c2-b10e08b38572.png) is impressive to me because it balances abstract(code <>) and concrete(tool box)
> > > > ![image](https://user-images.githubusercontent.com/7271329/244289011-5937b22b-31ad-4000-80a4-e1400ab67724.png) is a bit similar to another project in CKB ecosystem, [axon web3](https://github.com/axonweb3)
> > > > Which one is your favorite among all above, including [#23 (comment)](https://github.com/Magickbase/visual-style-guide/issues/23#issuecomment-1541471512)
> > > > @Daryl-L @PainterPuppets @yanguoyu @zhengjianhui
> > > 
> > > 
> > > Which one would you prefer @Daryl-L @PainterPuppets @yanguoyu
> > 
> > 
> > I prefer the last one.
> 
> Comes out that ![image](https://user-images.githubusercontent.com/7271329/250466809-0dda5bac-4de0-4dde-b85f-fb5c6f2aa1a3.png) ![image](https://user-images.githubusercontent.com/7271329/250466835-a6ec1b2c-03e9-45cb-8fc9-33b05617159f.png) ![image](https://user-images.githubusercontent.com/7271329/250466853-99f7a6df-ddb6-4c79-932e-5866cd60969f.png) are preferred by each one
> 
> Which one in the whole list(not only 3 above) do you pick @PainterPuppets

Feel great, the first and last style is a bit like Tencent hhhh, I prefer this purple
<img width="90" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/22258327/5fc26a02-fd41-4beb-9855-31dee5b37c56">

**Comment by Keith-CY** [comment]
Wow, diversity 🤔

**Comment by Kirl70** [comment]
We need to select a final logo for the subsequent official website design

**Comment by Keith-CY** [comment]
> We need to select a final logo for the subsequent official website design

I would like to pick 
![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/a28cf882-c3f0-451b-baf8-9fed8f398c9b)
as the final one with my project owner-privilege because each logo got 1 vote equally.

**Comment by Kirl70** [comment]
Logo resource link
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=19918%3A41963&mode=design&t=6M6PPoIRoPNHeg80-1
<img width="1049" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/9b1adeaf-3d9e-420c-bb5a-0dd6daa4f680">
