### ISSUE TITLE
Exploration of design styles for Magickbase website

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/visual-style-guide#24]
**Style 1:** 
The color scheme features a black background with white text. The page elements are designed with a sci-fi, cosmic, and futuristic direction.
First screen example: ![1](https://github.com/Magickbase/visual-style-guide/assets/106060898/55188961-3461-4bf3-a7e6-d3bfdace60f7)

https://github.com/Magickbase/visual-style-guide/assets/106060898/691196ae-afbc-4a68-b2d1-509941c4f1f9

Background reference: https://codepen.io/Kirl70/pen/zYmpXZY

**Style 2:** 
The color scheme revolves around a white background with black text. The page elements are designed using various gradient colors and crystal materials, with an overall emphasis on simplicity and cleanliness.
First screen example: 
![2](https://github.com/Magickbase/visual-style-guide/assets/106060898/28100bbb-1dcc-4dde-9c01-cbad8b178616)

Demo: https://my.spline.design/web2demo-e431ba50332773ea2de495d7ec940759/

**Style 3:** 
The page style primarily features a large area of bright colors. There is no dominant color scheme, and multiple colors are used for switching, combined with 3D elements.

First screen example: 
![3](https://github.com/Magickbase/visual-style-guide/assets/106060898/4534c094-7577-44f1-943b-37c7caac9d0f)

Demo: https://my.spline.design/untitled-78e24b18cb426b0828b2101f8b6fe870/

**Style 4:** 
The first screen utilizes a mouse-scrolling interaction to bring the text closer, symbolizing entry into the world of Magickbase. The overall style is characterized by a combination of multiple colors and cartoon graphics.

First screen example: 
![4](https://github.com/Magickbase/visual-style-guide/assets/106060898/b9e3739f-1f7a-4305-b1ca-f9ad0257ace8)

https://github.com/Magickbase/visual-style-guide/assets/106060898/d410fb32-16fc-4d07-8771-c042e7236e44

**Comment by Kirl70** [comment]
Any thoughts or suggestions @Keith-CY @Danie0918 @Sven-TBD

**Comment by Keith-CY** [comment]
They are all impressive!

My personal preference is **style 1**, **style 3**, **style 4**, **style 2**

BTW, what do the sheets in **style 4** mean

**Comment by Kirl70** [comment]
> They are all impressive!
> 
> My personal preference is **style 1**, **style 3**, **style 4**, **style 2**
> 
> BTW, what do the sheets in **style 4** mean

The background of Style 4 represents a scene of a bountiful wheat field being gently swept by the wind, but with a sci-fi color scheme.

**Comment by Danie0918** [comment]
According to the color style of Nervos, I prefer style 1,
But Style 2 would make it feel like our organization is more dynamic.

So can we add color or style to make us related to Nervos but unique and vibrant on the basis of black and white. I've thought of 2 ideas so far:

1. Use cartoon lines or special fonts to make the page interesting, you can refer to the following cases.
![image](https://github.com/Magickbase/visual-style-guide/assets/122437870/f4d50534-37f5-4b0e-8b46-2718b69af2de)
![image](https://github.com/Magickbase/visual-style-guide/assets/122437870/a50a1858-a290-4760-9bd6-df3d452a3bfc)

2. Add other colors, such as orange or blue, to make the page more vivid and full of technology, you can refer to the following case.

![image](https://github.com/Magickbase/visual-style-guide/assets/122437870/4d2b269b-77e8-47ee-a464-1b5554e6fd1f)

**Comment by Kirl70** [comment]
> According to the color style of Nervos, I prefer style 1, But Style 2 would make it feel like our organization is more dynamic.
> 
> So can we add color or style to make us related to Nervos but unique and vibrant on the basis of black and white. I've thought of 2 ideas so far:
> 
> 1. Use cartoon lines or special fonts to make the page interesting, you can refer to the following cases.
>    ![image](https://user-images.githubusercontent.com/122437870/241628030-f4d50534-37f5-4b0e-8b46-2718b69af2de.png)
>    ![image](https://user-images.githubusercontent.com/122437870/241628102-a50a1858-a290-4760-9bd6-df3d452a3bfc.png)
> 2. Add other colors, such as orange or blue, to make the page more vivid and full of technology, you can refer to the following case.
> 
> ![image](https://user-images.githubusercontent.com/122437870/241630745-4d2b269b-77e8-47ee-a464-1b5554e6fd1f.png)

Regarding colors, because we have a lot of products and each product has its own unique color, if we use a certain color too early on the homepage, it may cause style matching issues with different product introductions later on. Therefore, the safest option is not to define a main color on the homepage. If we adopt Style 1, its first screen will be a constantly changing dynamic style with colors that keep changing. Interesting page elements will be displayed in the remaining pages.

-----------------------------------

If there are no other objections, I will design the official website using Style 1.

**Comment by Keith-CY** [comment]
> > According to the color style of Nervos, I prefer style 1, But Style 2 would make it feel like our organization is more dynamic.
> > So can we add color or style to make us related to Nervos but unique and vibrant on the basis of black and white. I've thought of 2 ideas so far:
> > 
> > 1. Use cartoon lines or special fonts to make the page interesting, you can refer to the following cases.
> >    ![image](https://user-images.githubusercontent.com/122437870/241628030-f4d50534-37f5-4b0e-8b46-2718b69af2de.png)
> >    ![image](https://user-images.githubusercontent.com/122437870/241628102-a50a1858-a290-4760-9bd6-df3d452a3bfc.png)
> > 2. Add other colors, such as orange or blue, to make the page more vivid and full of technology, you can refer to the following case.
> > 
> > ![image](https://user-images.githubusercontent.com/122437870/241630745-4d2b269b-77e8-47ee-a464-1b5554e6fd1f.png)
> 
> Regarding colors, because we have a lot of products and each product has its own unique color, if we use a certain color too early on the homepage, it may cause style matching issues with different product introductions later on. Therefore, the safest option is not to define a main color on the homepage. If we adopt Style 1, its first screen will be a constantly changing dynamic style with colors that keep changing. Interesting page elements will be displayed in the remaining pages.
> 
> If there are no other objections, I will design the official website using Style 1.

LGTM, and a tiny detail in the preview is attractive to me

![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/1bdb95c0-f199-44c2-a2fd-a5e66b78193f)

There's a faintly visible sphere is present in the background, reminding me of the earth covered by blockchain nodes, very decentralized 😎. And the spots outside the earth look like satellites, very fantastic/starlink.
