### ISSUE TITLE
Magickbase official website design

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/visual-style-guide#25]
We are preparing a magickbase official website to enhance our brand influence, help users obtain our news, and convey our spirit.
___________________________________________________________________________________________________________________________________________

PRD:[https://lb84z6.axshare.com/](https://lb84z6.axshare.com/)

**Comment by Kirl70** [comment]
Please provide the English copy for the homepage, About Us, and the introduction pages for each product. Since the design draft will be in English, it's important to consider the spacing between elements based on the English text, which is usually longer than Chinese.

**Comment by Keith-CY** [comment]
> Please provide the English copy for the homepage, About Us, and the introduction pages for each product. Since the design draft will be in English, it's important to consider the spacing between elements based on the English text, which is usually longer than Chinese.

It can be found at https://github.com/Magickbase/shaping/issues/43#issuecomment-1509667793

Besides, a slight change in the slogan on the homepage was commented in PRD
![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/fcb7e484-bd4d-4828-a262-dc9bba41ee07)

The original description is

> Magickbase is a thriving company that's helping to lead the charge in the decentralized revolution. We're proud of the products we've built, the communities we've supported, and the impact we've made on the world. Also, we know that there's still a lot of work to do, and we're excited to keep pushing the boundaries of what's possible in the years to come.

It can be shortened to the following to be encouraging

> We're proud of the products we've built, the communities we've supported, and the impact we've made on the world, leading the charge in the decentralized revolution.

**Comment by Danie0918** [comment]
@Kirl70 I have completed the English translation of all pages on the basis of the copy provided by Keith-CY.

PRD Address：[https://lb84z6.axshare.com](https://lb84z6.axshare.com)

**Comment by Kirl70** [comment]
Other pages will be continuously updated:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=17481%3A39205&t=7m4jGSGEKh2cGbFA-1

**Comment by Kirl70** [comment]
The desktop version is completed. now starting to design the mobile version. 
Do the Neuron download and help documentation pages need to be designed for mobile devices?
@Danie0918

**Comment by Danie0918** [comment]
> The desktop version is completed. now starting to design the mobile version.
> Do the Neuron download and help documentation pages need to be designed for mobile devices?

Although the mobile client can't install Neuron Wallet, it can share the downloaded installation package, so it's still necessary to design the download page for mobile. For the help documentation pages this is applicable to mobile devices, so mobile pages are also needed.

**Comment by Kirl70** [comment]
The mobile page design has been completed.
