### ISSUE TITLE
Support mobile layout of nervos.org's roadmap page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#27]
The roadmap page was drafted by a foundation member because there was a bottleneck in the original designer.

The draft is as follows

![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/92e4c480-4acd-4c2e-91a1-e1c37441a27f)

It only covers the layout for desktop, so we need to add a draft for mobile correspondingly.

---

This issue comes from https://github.com/Magickbase/nervos-official-website/issues/175

**Comment by Kirl70** [comment]
Is there Figma or any design resources available for the desktop version? To maintain consistency with other pages, it would be best to provide design resources from Figma and the details for the mobile version of other pages.

<img width="815" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/32282140-705e-4d2a-8d66-7899db70a5bc">
<img width="1207" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/fc3e1df2-044b-438d-a694-f23ad783be18">
<img width="1319" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/7c8db823-b37c-4ceb-b067-e7449fa5f80e">

**Comment by Keith-CY** [comment]
> Is there Figma or any design resources available for the desktop version? To maintain consistency with other pages, it would be best to provide design resources from Figma and the details for the mobile version of other pages.
> 
> <img alt="image" width="815" src="https://user-images.githubusercontent.com/106060898/250783658-32282140-705e-4d2a-8d66-7899db70a5bc.png"> <img alt="image" width="1207" src="https://user-images.githubusercontent.com/106060898/250783824-fc3e1df2-044b-438d-a694-f23ad783be18.png"> <img alt="image" width="1319" src="https://user-images.githubusercontent.com/106060898/250783983-7c8db823-b37c-4ceb-b067-e7449fa5f80e.png">

Sure, the figma is available at https://www.figma.com/file/fMWK8ZGROCdfOa7nmmUDHz/Nervos.org-R4?type=design&node-id=5215-842&mode=design&t=l8TPNURExQFSvHEy-0

**Comment by Kirl70** [comment]
The mobile design draft for this page:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=19500%3A40379&mode=design&t=2axernEJb7BQfUsP-1
![Nervos The Journey Roadmap - Mobile](https://github.com/Magickbase/visual-style-guide/assets/106060898/49e7c042-9223-4abd-acbb-9ff327bf5163)
