### ISSUE TITLE
Optimize author list of nervos.org

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#29]
This issue comes from https://github.com/NervosEducationHub/EducationHubArticles/issues/29#issuecomment-1646932587

---

Now the author list displays multiple authors with stacked avatars and the first author's name.

![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/a0d88f42-c3e9-4186-b33f-68ab119d0849)
page: https://www.nervos.org/knowledge-base/understanding_nervos_ckb_issuance_model

![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/6aec7fe5-a76d-491d-a23e-5e36f1b4cc54)
page: https://www.nervos.org/knowledge-base

It's not fair for other authors, so it's expected to show all of them by interaction mentioned at 
https://github.com/NervosEducationHub/EducationHubArticles/issues/29#issuecomment-1646932587

![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/14704825-6552-4c52-93da-453e3ab0665e)
or
![image](https://github.com/Magickbase/visual-style-guide/assets/7271329/78a0a896-ac56-44c0-a8db-8f90ea915750)

Either is good for the improvement, and can be redesigned by @Kirl70

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=22063%3A22333&mode=design&t=TCwalGkUfcvc8qNC-1

When there is enough space, display the avatars of up to 5 authors, and use the 6th icon to show the total number of authors:
<img width="687" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/ca527b63-eaa8-43c1-ba6f-acbff29dde63">


When space is limited, only display the avatar of the first author and the total number of authors:
<img width="420" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/ce3cc119-cba8-4b4c-9a19-bacf6b44777b">
