### ISSUE TITLE
gwscan ui updates since the first design confirmed

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#3]
1. raw data tab was added in tx page and block page: https://v1.testnet.gwscan.com/tx/0x998fff22dec4567e0a11e4d8819309deee77d620a599b9a13745ca0d4215745e?tab=raw-data
https://v1.testnet.gwscan.com/block/0x671c0031ade707cb49211f8208cdc383bd8239181d3f3a16cfd6709114044e16?tab=raw-data
![image](https://user-images.githubusercontent.com/7271329/180718961-7048e080-3f5d-4ea5-8b90-26d977c8fb2e.png)
![image](https://user-images.githubusercontent.com/7271329/180719001-43dd6291-4344-412d-ad16-f61f24a04957.png)

2. tx list on home page shows `failed` icon if txn is failed
3. contract page add a `verify status` field, with value of `verified` or `verify it`:
https://v1.testnet.gwscan.com/account/0x890713a48c035903f81ca88f87cc43cf11cae081
![image](https://user-images.githubusercontent.com/7271329/180718878-5a6ee32f-e9bd-4c39-b07c-c30643893eff.png)

4. transaction list and transfer list of a specific account has 'in/out/self' tag:https://v1.testnet.gwscan.com/account/0x52bf58425cad0b50ffca8dbe5447dce9420a2610
![image](https://user-images.githubusercontent.com/7271329/180718812-a4b5bdf4-8230-4a16-a0d3-b4c217a68a6a.png)

5. `from/to` in tx list shows its custom name if there is
![image](https://user-images.githubusercontent.com/7271329/180719141-af83679b-636d-4845-a396-ab3c51c0b126.png)

**Comment by Keith-CY** [comment]
Here're some features updated on the previous UI since the new UI has been confirmed, please also combine them into the new design @Kirl70

**Comment by Kirl70** [comment]
1. tx page https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2227%3A13755
<img width="849" alt="image" src="https://user-images.githubusercontent.com/106060898/181162279-30b7581a-8c27-4200-a052-d672a91f4e59.png">


block page https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2232%3A14046
<img width="855" alt="image" src="https://user-images.githubusercontent.com/106060898/181162315-6408060b-ef45-4b83-abd4-d1e9bd74e91d.png">


2.home page https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A2
<img width="703" alt="image" src="https://user-images.githubusercontent.com/106060898/181162340-b31d60e7-5905-428a-a6c3-4babd2562eaf.png">

3.contract page https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A2098
<img width="795" alt="image" src="https://user-images.githubusercontent.com/106060898/181162379-b1a1206e-7743-474e-a358-47da2654a567.png">


4/5. tx list https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2319%3A17211

<img width="866" alt="image" src="https://user-images.githubusercontent.com/106060898/181197685-4c85444b-49e6-4881-bd98-3ea8d54d750b.png">

**Comment by Keith-CY** [comment]
# 6. Add filter in list
![image](https://user-images.githubusercontent.com/7271329/182097020-a00c4f4f-921c-42b7-8b79-76b496f07b77.png)

**Comment by Kirl70** [comment]
> # 6. Add filter in list
> ![image](https://user-images.githubusercontent.com/7271329/182097020-a00c4f4f-921c-42b7-8b79-76b496f07b77.png)

1. filtered by block number 
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A1209
<img width="952" alt="image" src="https://user-images.githubusercontent.com/106060898/182154525-6ae1486d-74cb-45c2-bb1d-1dfc1f1ae870.png">

2. filtered by from / to
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=183%3A4057
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/106060898/182154731-a6c5e3cd-2157-450d-aead-6380f050e064.png">

3. filtered by age (from and to)
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2319%3A17211
<img width="843" alt="image" src="https://user-images.githubusercontent.com/106060898/182154959-ee6e5654-6b8a-4e75-a962-0137c6663488.png">

4. filtered by token type
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=183%3A5028
<img width="805" alt="image" src="https://user-images.githubusercontent.com/106060898/182155151-6fd57fc0-7711-49d7-86fc-bcf94a9fce9b.png">

5. sorted by balance / sorted by tx count
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2431%3A21065
<img width="934" alt="image" src="https://user-images.githubusercontent.com/106060898/182155536-68f01f5e-77ea-4466-9f7b-73d044ff2c94.png">

6. sorted by total supply(circulating supply) / sorted by holders / sorted by name / filtered by name (fuzzy)
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A2057
<img width="930" alt="image" src="https://user-images.githubusercontent.com/106060898/182155747-18015c95-0c2a-4b64-9b24-9a69a93c93d1.png">

7. no related content
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3049%3A19069
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/106060898/182271687-949f7325-0f23-46fe-9837-9781bc1a0bb2.png">
