### ISSUE TITLE
Overview Page Adjustment

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/visual-style-guide#30]
According to the [requirement description](https://github.com/Magickbase/neuron-public-issues/pull/227#issuecomment-1639209340), the previously separate modules for `Receive` and `Send` will be merged with the `Balance` module into one.

**Comment by Kirl70** [comment]
The current page design is already completed. However, in my opinion, if we directly merge the existing color modules, it may result in an unbalanced color proportion on the page. Perhaps we can consider using a different style for the cards. Therefore, I have prepared a contrasting proposals. Which one do you think is better?  @Keith-CY @Danie0918 

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=22119%3A23433&mode=design&t=4xlANklt8h23jD9L-1
<img width="882" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/4f05fde6-3794-4a52-bd9b-952199f7fb31">

**Comment by Danie0918** [comment]
> The current page design is already completed. However, in my opinion, if we directly merge the existing color modules, it may result in an unbalanced color proportion on the page. Perhaps we can consider using a different style for the cards. Therefore, I have prepared a contrasting proposals. Which one do you think is better? @Keith-CY @Danie0918

I prefer the right side option, the buttons will be more prominent and easier for the user to maneuver.

**Comment by Keith-CY** [comment]
> > The current page design is already completed. However, in my opinion, if we directly merge the existing color modules, it may result in an unbalanced color proportion on the page. Perhaps we can consider using a different style for the cards. Therefore, I have prepared a contrasting proposals. Which one do you think is better? @Keith-CY @Danie0918
> 
> I prefer the right side option, the buttons will be more prominent and easier for the user to maneuver.

upvote
