### ISSUE TITLE
CKB explorer homepage countdown halving banner and page

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/visual-style-guide#32]
According to the [requirement](https://github.com/Magickbase/ckb-explorer-public-issues/issues/365)

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=23176%3A42184&mode=design&t=Be3iLni68kFnBboy-1

1. Animation effect for the halving countdown banner: When the mouse hovers over the banner area and is scrolled, the button can have an Easter egg effect, displaying the remaining days for halving or other text. 
The banner conveys the meaning that CKB is progressing towards halving on the path of block assembly.

https://github.com/Magickbase/visual-style-guide/assets/106060898/7491cad1-bc69-4a25-8239-9664772ba12f






2. Animation effect for the `Halved completion` banner. 
The banner signifies the successful halving, forming the Nervos logo and the letters "CKB" through block assembly. Blocks rotate and float around them as a celebration.

https://github.com/Magickbase/visual-style-guide/assets/106060898/41025347-22d6-443a-a78d-b9446bac927d

**Comment by Kirl70** [comment]
Any ideas from @Keith-CY @Danie0918

**Comment by Keith-CY** [comment]
It would be better to show the left time in the banner directly so users get the key information instantly and easily

**Comment by Keith-CY** [comment]
BTW we've tried the metal effect but it failed LOL, performance was impacted on some computers

**Comment by Kirl70** [comment]
> It would be better to show the left time in the banner directly so users get the key information instantly and easily

The prototype's banner does not display the date, although it was present in the deprecated prototype.

<img width="1051" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/634f9545-1278-4cf2-a1b8-4c7e45a22b8d">

<img width="1215" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/ae7a4f20-698f-4d51-8249-91f68688a0dd">

I thought that users needed to click `Know More` to see the date information.

**Comment by Kirl70** [comment]
> BTW we've tried the metal effect but it failed LOL, performance was impacted on some computers

This animation effect was created using the Spline tool, which supports exporting code for direct use by developers. It might be worth exploring since this software's code will also be used on the official website.

Developer documentation: https://github.com/splinetool/react-spline
Official documentation: https://docs.spline.design/77c32288501a479fa8bc5e787f1e0878

**Comment by Danie0918** [comment]
> > It would be better to show the left time in the banner directly so users get the key information instantly and easily
> 
> The prototype's banner does not display the date, although it was present in the deprecated prototype.
> 
> <img alt="image" width="1051" src="https://user-images.githubusercontent.com/106060898/261180888-634f9545-1278-4cf2-a1b8-4c7e45a22b8d.png"> <img alt="image" width="1215" src="https://user-images.githubusercontent.com/106060898/261181078-ae7a4f20-698f-4d51-8249-91f68688a0dd.png">
> I thought that users needed to click `Know More` to see the date information.

The first version of the design was designed as a single event, but subsequent consideration was given to making it a permanent page, so changes were made.

It's currently approaching the first halving, and I've pondered that it would be better to release the remaining time in this case, and I'll adjust the PRD.

**Comment by Kirl70** [comment]
Added an alternative option: The teaser banner could use a background image approach.

<img width="1150" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/637a1179-8db7-40d1-bf29-b7585fb2890e">

### 
### 

The background effect is related to the background of the details page:

<img width="1254" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/84490360-f073-4455-a173-c90528ec1271">

### 
### 
The already halved banner could also use a background image approach. However, if performance allows, some animated effects could be applied to the top blocks.


https://github.com/Magickbase/visual-style-guide/assets/106060898/948d3234-75d1-4944-b74f-62867c5b1458


Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=24228%3A40691&mode=design&t=3WM6kXyVNvFzY0cS-1

**Comment by Keith-CY** [comment]
> Added an alternative option: The teaser banner could use a background image approach.
> 
> <img alt="image" width="1150" src="https://user-images.githubusercontent.com/106060898/263571701-637a1179-8db7-40d1-bf29-b7585fb2890e.png">
> The background effect is related to the background of the details page:
> 
> <img alt="image" width="1254" src="https://user-images.githubusercontent.com/106060898/263571752-84490360-f073-4455-a173-c90528ec1271.png">
> The already halved banner could also use a background image approach. However, if performance allows, some animated effects could be applied to the top blocks.
> 
>  having-new.mp4 
> Design Draft: [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=24228%3A40691&mode=design&t=3WM6kXyVNvFzY0cS-1](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=24228%3A40691&mode=design&t=3WM6kXyVNvFzY0cS-1)

LGTM, except the button `know more` in PRD can be renamed as `learn more`, which is more common.

Please have a review @Danie0918 @Sven-TBD

**Comment by Danie0918** [comment]
Sorry, I forgot to reply, the design is ok.
 
> LGTM, except the button `know more` in PRD can be renamed as `learn more`, which is more common.

Let's change it to learn more. @Kirl70

**Comment by Kirl70** [comment]
> Sorry, I forgot to reply, the design is ok.
> 
> > LGTM, except the button `know more` in PRD can be renamed as `learn more`, which is more common.
> 
> Let's change it to learn more. @Kirl70

The design draft has been adjusted.
<img width="728" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/aa94139e-d2b2-4045-b54d-bb5c5cff96e7">

**Comment by Kirl70** [comment]
Countdown font file:
[digital-7.zip](https://github.com/Magickbase/visual-style-guide/files/12483564/digital-7.zip)

<img width="705" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/f1b63d8d-c183-4e78-84a2-1070077f1204">
