### ISSUE TITLE
Design the WalletConnect module for Neuron.

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/visual-style-guide#34]
According to the [requirement](https://i2aurv.axshare.com/?id=jm16ku&g=1&p=walletconnect-neuron)

**Comment by Kirl70** [comment]
Design Draft(15-1~15-10):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=25094%3A26491&mode=design&t=PPbJMAcjodhwqrx0-1

**Comment by Kirl70** [comment]
@Sven-TBD Please review the design draft.

**Comment by poor-defined** [comment]
Reviewed, I have commented on Figma.
