### ISSUE TITLE
New logo for sub-org named "Random Walk"

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#39]
We have declared a sub-org named "Random Walk" for colleagues to work in Japan. The org is defined as a freelance team consisting of programmers and designers, dedicated to creative design and implementation.

The logo will be used in material for visa application, so it's better to be nice on paper or displayed in greyscale print.

But it would be great if the logo could be colored in various themes, similar to 
<img width="714" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/7271329/b221057c-8113-4785-810c-92d3ade20801">

**Comment by Kirl70** [comment]
Let's decide on the design of the logo first, and after that, I will work on the logo's color variations and print files.

The following is the LOGO scheme:

<img width="1272" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/14abc362-dab3-43c2-97df-925f55478267">

**Comment by Keith-CY** [comment]
> Let's decide on the design of the logo first, and after that, I will work on the logo's color variations and print files.
> 
> The following is the LOGO scheme:
> 
> <img alt="image" width="1272" src="https://user-images.githubusercontent.com/106060898/281681461-14abc362-dab3-43c2-97df-925f55478267.png">

I found the 4th one to be great, clear, and inspiring.

**Comment by Kirl70** [comment]
Other color schemes for the logo:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=29354%3A25944&mode=design&t=4IKgNfw0eFmWW2iy-1
<img width="598" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/3f5110a8-a117-4c3f-92f3-a00fde9671d9">


Printable logo files:
[logo-randomwalk.zip](https://github.com/Magickbase/visual-style-guide/files/13423196/logo-randomwalk.zip)

**Comment by Keith-CY** [comment]
> Other color schemes for the logo: [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=29354%3A25944&mode=design&t=4IKgNfw0eFmWW2iy-1](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=29354%3A25944&mode=design&t=4IKgNfw0eFmWW2iy-1) <img alt="image" width="598" src="https://user-images.githubusercontent.com/106060898/284500248-3f5110a8-a117-4c3f-92f3-a00fde9671d9.png">
> 
> Printable logo files: [logo-randomwalk.zip](https://github.com/Magickbase/visual-style-guide/files/13423196/logo-randomwalk.zip)

Nice work 👍
