### ISSUE TITLE
gwscan ui is going to add some features

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#4]
1. account page add a QR Code of address, similar to https://etherscan.io/address/0xea674fdde714fd979de3edf0f56aa9716b898ec8 (button next to the address)
2. Token list would split `UAN`'s display name into 3 parts(symbol, bridge, origin): https://github.com/Magickbase/godwoken_explorer/issues/772
e.g. a token named `DAI (via Force Bridge from ETH)` will split into 3 columns `name: DAI`, `bridge: Force Bridge`, `origin: ETH`
3. Transaction list would add one more column `method id/name`, similar to https://etherscan.io/txs, ref: https://github.com/Magickbase/godwoken_explorer/issues/762

**Comment by Keith-CY** [comment]
Some feedback from the foundation and community

1. super high precision of value in the tx list is meaningless, say, `0.01231239184829485`, we can truncate it or make it partially inconspicuous.
2. `transaction type` may be not so useful generally so it can be removed from the transaction list

**Comment by Keith-CY** [comment]
> Some feedback from the foundation and community
> 
> 1. super high precision of value in the tx list is meaningless, say, `0.01231239184829485`, we can truncate it or make it partially inconspicuous.
> 2. `transaction type` may be not so useful generally so it can be removed from the transaction list

Do you have any idea about improving visual experience on a number of `super high precision` @Kirl70

**Comment by Keith-CY** [comment]
Two features requested from community

1. add `log index` in the `transfer list` in a transaction page and turn the order to `asc`
2. add `index` in the `transaction list` in a block page and turn the order to `asc`

**Comment by Kirl70** [comment]
> > Some feedback from the foundation and community
> > 
> > 1. super high precision of value in the tx list is meaningless, say, `0.01231239184829485`, we can truncate it or make it partially inconspicuous.
> > 2. `transaction type` may be not so useful generally so it can be removed from the transaction list
> 
> Do you have any idea about improving visual experience on a number of `super high precision` @Kirl70


> 

Based on the afternoon discussion, combining   questions 4 and 5 of #3 , make the following adjustments

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A920

<img width="866" alt="image" src="https://user-images.githubusercontent.com/106060898/181197303-f26b1efa-3f77-40a5-9277-77fd96690647.png">


>

**Comment by Keith-CY** [comment]
Feedback from foundation

Since we are using a new rule on `token symbol`(https://github.com/nervosnetwork/rfcs/blob/a092218b8f3ba9b6616ff41bd56a5a75d42efaf7/rfcs/0000-universal-asset-notation/0000-universal-asset-notation.md), the `token symbol` in transfer list becomes too messy once records grow, e.g. 
```
1.234567890123456 USDC.gw|fb.ckb
1,231.234567890126 USDT.gw|fb.ckb
1.23456789012346 USDC.gw|fb.eth
```

Could we simplify the `token identify` in some way, e.g. using a compound logo to deliver `token, bridge, origin` visually?
![image](https://user-images.githubusercontent.com/7271329/181143263-e15363ee-bdb5-42c6-9d10-f3b5a3b84db6.png)

**Comment by Keith-CY** [comment]
> Feedback from foundation
> 
> Since we are using a new rule on `token symbol`([nervosnetwork/rfcs@`a092218`/rfcs/0000-universal-asset-notation/0000-universal-asset-notation.md](https://github.com/nervosnetwork/rfcs/blob/a092218b8f3ba9b6616ff41bd56a5a75d42efaf7/rfcs/0000-universal-asset-notation/0000-universal-asset-notation.md)), the `token symbol` in transfer list becomes too messy once records grow, e.g.
> 
> ```
> 1.234567890123456 USDC.gw|fb.ckb
> 1,231.234567890126 USDT.gw|fb.ckb
> 1.23456789012346 USDC.gw|fb.eth
> ```
> 
> Could we simplify the `token identify` in some way, e.g. using a compound logo to deliver `token, bridge, origin` visually? ![image](https://user-images.githubusercontent.com/7271329/181143263-e15363ee-bdb5-42c6-9d10-f3b5a3b84db6.png)

Other pages include the long symbol
1. asset list of a specific account https://v1.gwscan.com/account/0x8166593d7eff901c64373047123774cb1ac4fa0c?tab=assets
2. token list https://v1.gwscan.com/zh-CN/tokens/bridge
3. transfer list of a specific transaction https://v1.gwscan.com/tx/0x5a1f89ae74452b1d4f81bb6ddf362751449abf315bbfd8c71c0d057107a48673
4. transfer list of a specific account https://v1.gwscan.com/account/0xccf1d7d814c4a2d6e6de23cb4ac1da1cc4e909ba?tab=erc20

**Comment by Kirl70** [comment]
> 1. account page add a QR Code of address, similar to https://etherscan.io/address/0xea674fdde714fd979de3edf0f56aa9716b898ec8 (button next to the address)
> 2. Token list would split `UAN`'s display name into 3 parts(symbol, bridge, origin): [Refine UAN display godwoken_explorer#772](https://github.com/Magickbase/godwoken_explorer/issues/772)
>    e.g. a token named `DAI (via Force Bridge from ETH)` will split into 3 columns `name: DAI`, `bridge: Force Bridge`, `origin: ETH`
> 3. Transaction list would add one more column `method id/name`, similar to https://etherscan.io/txs, ref: [[Feature Request] Support querying method_id/method_name of a transaction godwoken_explorer#762](https://github.com/Magickbase/godwoken_explorer/issues/762)

1. account page add a QR Code of address 
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=183%3A4057
<img width="855" alt="image" src="https://user-images.githubusercontent.com/106060898/181414238-90b717ed-f0cd-4d2e-83b0-e4751ab146b0.png">

2.Token list optimization
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A2057
<img width="892" alt="image" src="https://user-images.githubusercontent.com/106060898/181414418-3410c196-1cd2-4d42-aed8-3a948f38f441.png">

3. Transaction list add `method id/name`
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=2319%3A17211
<img width="904" alt="image" src="https://user-images.githubusercontent.com/106060898/181414621-625d6e69-b27b-4b16-a229-409940bef978.png">

**Comment by Kirl70** [comment]
> > Feedback from foundation
> > Since we are using a new rule on `token symbol`([nervosnetwork/rfcs@`a092218`/rfcs/0000-universal-asset-notation/0000-universal-asset-notation.md](https://github.com/nervosnetwork/rfcs/blob/a092218b8f3ba9b6616ff41bd56a5a75d42efaf7/rfcs/0000-universal-asset-notation/0000-universal-asset-notation.md)), the `token symbol` in transfer list becomes too messy once records grow, e.g.
> > ```
> > 1.234567890123456 USDC.gw|fb.ckb
> > 1,231.234567890126 USDT.gw|fb.ckb
> > 1.23456789012346 USDC.gw|fb.eth
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could we simplify the `token identify` in some way, e.g. using a compound logo to deliver `token, bridge, origin` visually? ![image](https://user-images.githubusercontent.com/7271329/181143263-e15363ee-bdb5-42c6-9d10-f3b5a3b84db6.png)
> 
> Other pages include the long symbol
> 
> 1. asset list of a specific account https://v1.gwscan.com/account/0x8166593d7eff901c64373047123774cb1ac4fa0c?tab=assets
> 2. token list https://v1.gwscan.com/zh-CN/tokens/bridge
> 3. transfer list of a specific transaction https://v1.gwscan.com/tx/0x5a1f89ae74452b1d4f81bb6ddf362751449abf315bbfd8c71c0d057107a48673
> 4. transfer list of a specific account https://v1.gwscan.com/account/0xccf1d7d814c4a2d6e6de23cb4ac1da1cc4e909ba?tab=erc20

1. asset list of a specific account
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=183%3A5360
<img width="952" alt="image" src="https://user-images.githubusercontent.com/106060898/181415259-64d7ee6b-b85b-477c-af52-93eff14319ce.png">

2.token list
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=67%3A2057
<img width="833" alt="image" src="https://user-images.githubusercontent.com/106060898/181415353-2ba8b7b9-a0b8-4a82-a970-c3e336bfb4b1.png">

3.transfer list of a specific transaction 
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A1501
<img width="753" alt="image" src="https://user-images.githubusercontent.com/106060898/181415639-709e894c-11b1-40bd-9a0c-67f7239756fb.png">

4.transfer list of a specific account
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=183%3A5028
<img width="945" alt="image" src="https://user-images.githubusercontent.com/106060898/181415799-933c2648-c479-49c1-b1db-7f1479e0a702.png">

**Comment by Keith-CY** [comment]
> Two features requested from community
> 
> 1. add `log index` in the `transfer list` in a transaction page and turn the order to `asc`
> 2. add `index` in the `transaction list` in a block page and turn the order to `asc`

These two are not added yet and because transfer list is simple, I prepend `log index` in the list as https://github.com/Magickbase/godwoken-explorer-ui/pull/389

**Comment by Keith-CY** [comment]
Hovering on `Token Logo` and showing `Originated from CKB` is fine when all tokens have a logo, but information will be lost when lack of token's logo(showing a default logo), users can only get the `origin` from the tooltip but don't know which token is bridged.

So I replaced `Originated from CKB` with the token's display name, such as `YOK (via Godwoken Bridge from CKB), for clarity. 


![Image](https://user-images.githubusercontent.com/7271329/183300012-512d9888-1443-4d7d-8de2-905232417e7e.png)

Besides, I added a toggle in this column to change logo into token name for mobile users(get the token info without touching the logo).


![Image](https://user-images.githubusercontent.com/7271329/183300105-480a1f7b-f363-426d-b84a-f0baef7e7b51.png)

**Comment by Keith-CY** [comment]
1. account page adds a QR Code of address: new issue https://github.com/Magickbase/godwoken_explorer/issues/812
2. Token list would split UAN's display name into 3 parts(symbol, bridge, origin): new issue https://github.com/Magickbase/godwoken_explorer/issues/772
3. Transaction list would add one more column method id/name: new issue https://github.com/Magickbase/godwoken_explorer/issues/762
4. super high precision of value in the tx list is meaningless, say, 0.01231239184829485, we can truncate it or make it partially inconspicuous: design draft https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A1209
5. transaction type may be not so useful generally so it can be removed from the transaction list: updated
6. add log index in the transfer list in a transaction page and turn the order to asc: new issue https://github.com/Magickbase/godwoken_explorer/issues/793

All tasks have their own issues so this issue could be closed
