### ISSUE TITLE
Lumos Logo

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/visual-style-guide#40]
Lumos: https://github.com/ckb-js/lumos

![image](https://github.com/Magickbase/visual-style-guide/assets/122437870/12cacfa5-954c-4b2c-b1af-ab9d17096c10)

**Comment by Keith-CY** [comment]
@homura does lumos have its own logo, which can be appended in a list as other projects?

**Comment by homura** [comment]
> @homura does lumos have its own logo, which can be appended in a list as other projects?

AFAIK, lumos only has a banner image, but no logo

**Comment by Kirl70** [comment]
The following is the LOGO scheme:

<img width="940" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/67da98e8-39a6-43cb-89dc-b27e4f04e2b9">

**Comment by Danie0918** [comment]
![image](https://github.com/Magickbase/visual-style-guide/assets/122437870/ed07bdbe-a87b-4eba-8241-0831e8c2d9a1)

I prefer 5, which combines both simplicity and lumos. What do you think? @Keith-CY @homura

**Comment by homura** [comment]
I prefer the first option since it's closer to the "Lumos" spell's effect, which lights up the surrounding area.

**Comment by Keith-CY** [comment]
I prefer 5 because <del>I found `N` in the logo</del> it's neat and good for variation
<img width="167" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/7271329/c8969e57-3d16-4df8-9688-052a9d41bd07">

and 4, which reminds me of light bands, busy roads, etc.
<img width="203" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/7271329/46733fd1-15b6-4989-9b61-65f829f654ab">

**Comment by poor-defined** [comment]
I like the first one and fifth one. The first one looks very refined; it would be nice if it could be made a bit flatter. The fifth one is also very good, with its regular outline being quite appealing.

**Comment by Danie0918** [comment]
@Kirl70 OK,let's output option 5.

**Comment by Kirl70** [comment]
> @Kirl70 OK,let's output option 5.

LOGO Resources:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=31115%3A2245&mode=design&t=Pj2nXbsFWKWpWvz4-1
<img width="630" alt="image" src="https://github.com/Magickbase/visual-style-guide/assets/106060898/3417a63d-bff5-4744-a79b-9c7767ddd2dc">
