### ISSUE TITLE
Loading Animation based on the logo

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#42]
<img width="769" alt="image" src="https://github.com/user-attachments/assets/4bfa4b71-d3b0-413a-bdc9-4d2623b3d88b">

![image](https://github.com/user-attachments/assets/a6af681e-c3a3-4db2-a06b-2828112c41c3)

are super great for a loading animation, e.g. shining laser, dancing flames, spinning lines for the background, and vortex in the middle.

Can we have one as the loading animation on the web3 platform?

**Comment by Kirl70** [comment]
Design Draft:

https://github.com/user-attachments/assets/ede1468d-81cf-4ea8-93a4-3421802d57a4



https://github.com/user-attachments/assets/7310fdbc-19ba-4892-bced-0b29a217fe04



https://github.com/user-attachments/assets/28dfb7f5-3c6d-44e4-b648-a31692d0f81b

**Comment by Keith-CY** [comment]
> Design Draft:
> 
>  Loading.C02.mp4 
>  Loading.C01.mp4 
>  Loading.C03.mp4

Animation 1 and 2 are both good, but the background of animation 2 is different from logo 8, can we use the background of logo 8? Like a spinning whirlpool.

https://giphy.com/gifs/deep-wash-laundry-3ohhwvBqI1BE1o3196

https://codepen.io/RyanWarner/pen/AGjqLN

Animation 3 is negligible when it's in a small size. Maybe we can make the arm/flame waving
<img width="180" alt="image" src="https://github.com/user-attachments/assets/287c3c7a-d4f6-4f21-9c83-b096540c5b18">
https://www.youtube.com/watch?v=bRXrL-8CTmg&t=24s

**Comment by Kirl70** [comment]
> > Design Draft: 
> > Loading.C02.mp4 
> > Loading.C01.mp4 
> > Loading.C03.mp4
> 
> Animation 1 and 2 are both good, but the background of animation 2 is different from logo 8, can we use the background of logo 8? Like a spinning whirlpool.
> 
> https://giphy.com/gifs/deep-wash-laundry-3ohhwvBqI1BE1o3196
> 
> https://codepen.io/RyanWarner/pen/AGjqLN
> 
> Animation 3 is negligible when it's in a small size. Maybe we can make the arm/flame waving <img alt="image" width="180" src="https://private-user-images.githubusercontent.com/7271329/356501525-287c3c7a-d4f6-4f21-9c83-b096540c5b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTQ1MjQsIm5iZiI6MTcyMzQ1NDIyNCwicGF0aCI6Ii83MjcxMzI5LzM1NjUwMTUyNS0yODdjM2M3YS1kNGY2LTRmMjEtOWM4My1iMDk2NTQwYzViMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDkxNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVkYzA5Mjc4ODRhMmQ2MzNmNDBjYmU5NmY2NDljNDIzYzNlNjc2YjRhN2ZmZjBjY2I3MTExZWJjZTBmZTI4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iLItqC5lXO1dLCpBm7Yrz59krN05yZxYHFmC95ce9Ig"> https://www.youtube.com/watch?v=bRXrL-8CTmg&t=24s

The shape of logo 8 looks a bit messy when it rotates, so I made a slight adjustment to the shape


https://github.com/user-attachments/assets/aa86fcbf-846d-4ef8-9fb9-94b413ca063d


https://github.com/user-attachments/assets/1eb61314-13ae-485e-ada0-75122f39bc51

**Comment by Keith-CY** [comment]
LGTM
