### ISSUE TITLE
Draft Design for a Web3 Platform

### ISSUE THREAD

**Issue by Kirl70** [Magickbase/visual-style-guide#43]

**Comment by Kirl70** [comment]
Based on discussions with @Sven-TBD , I have created two different page styles for both the homepage and the search pop-up page. Additionally, I have developed two different primary color schemes for the dark theme.

Dark Style:

https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=40623-57537&t=UMeTX44uhrJTr2Gj-1

<img width="877" alt="image" src="https://github.com/user-attachments/assets/bf900919-4f7b-409f-86bd-9adbd296a3de">

Light Style:

https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=40623-58285&t=UMeTX44uhrJTr2Gj-1
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/9d7286bf-24b3-4145-a87a-c29286f79fe2">

**Comment by Kirl70** [comment]
Additionally, I have a few Landing Page styles in mind that I find quite suitable.

https://www.framer.com/marketplace/template/taskify/

https://www.framer.com/marketplace/template/courseos/

https://webflow.com/templates/html/desinspirationx-directory-website-template

@Keith-CY @Sven-TBD please check

**Comment by Keith-CY** [comment]
> Additionally, I have a few Landing Page styles in mind that I find quite suitable.
> 
> [framer.com/marketplace/template/taskify](https://www.framer.com/marketplace/template/taskify/)
> 
> [framer.com/marketplace/template/courseos](https://www.framer.com/marketplace/template/courseos/)
> 
> [webflow.com/templates/html/desinspirationx-directory-website-template](https://webflow.com/templates/html/desinspirationx-directory-website-template)
> 
> @Keith-CY @Sven-TBD please check

Taskify looks good to me

**Comment by Kirl70** [comment]
I will use this version as the main design style to design the other pages.
<img width="946" alt="image" src="https://github.com/user-attachments/assets/1ed4c0c1-1769-4107-93a8-5f7f7ecccc89">
