### ISSUE TITLE
Add NFT in ckb explorer and godwoken explorer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#5]
We are going to support NFTs in ckb explorer and godwoken explorer, the product design is almost the same as https://etherscan.io/tokens-nft

1. nft collection list
2. nft collection detail
3. nft item detail
4. nft transfer list
5. nft inventory
6. user's nft list

---

PRD in text
- GwScan: https://github.com/Magickbase/godwoken_explorer/issues/689#issuecomment-1197710486
- CKB Explorer: https://github.com/Magickbase/ckb-explorer-public-issues/issues/32

sidenote: CKB Explorer has a basic UI of `user's nft list`

**Comment by Keith-CY** [comment]
We could start with GwScan first

**Comment by Keith-CY** [comment]
Any questions about the PRD are welcome @Kirl70 @qiweiii @FrederLu

**Comment by Kirl70** [comment]
1.  nft collection list
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3205%3A18937
<img width="846" alt="image" src="https://user-images.githubusercontent.com/106060898/182511084-109b572d-3fb7-4160-a1c0-7a3a1c75981e.png">

2. nft detail activity list
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3205%3A19091
<img width="858" alt="image" src="https://user-images.githubusercontent.com/106060898/182520134-bbeb02f5-d6f0-4a3f-9eac-004cc9ba2172.png">

3. nft detail holders list
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3205%3A19422
<img width="887" alt="image" src="https://user-images.githubusercontent.com/106060898/183324133-fdad9cef-bdbc-4347-9e55-d7606460f8ac.png">
4. nft detail Inventory list
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3205%3A19528
<img width="867" alt="image" src="https://user-images.githubusercontent.com/106060898/182314039-bf8a089c-7127-48ec-a89c-2ed8f02e0058.png">

5. nft item detail
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3205%3A19677
<img width="873" alt="image" src="https://user-images.githubusercontent.com/106060898/182314186-eda48bc4-5a9a-46ce-bef5-67b22af8c089.png">

6. user's nft list
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3205%3A19996
<img width="869" alt="image" src="https://user-images.githubusercontent.com/106060898/182314340-d8b2a2b7-ff6c-41ca-9d53-0351ca7e93d7.png">

**Comment by Keith-CY** [comment]
I've checked the design and think everything is OK. We will start this work next week if there are no other feedbacks. @qiweiii @FrederLu

**Comment by Keith-CY** [comment]
If no more feedback, please open a new issue with ETA. of each page and then we can share the work @qiweiii

**Comment by Kirl70** [comment]
CKB Explorer :

1.NFT Collection List
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3747%3A20662
<img width="804" alt="image" src="https://user-images.githubusercontent.com/106060898/183369244-07c02aa8-e65f-415d-8ffb-c7b154db5510.png">

2.NFT Detail Transfers
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3747%3A20821
<img width="805" alt="image" src="https://user-images.githubusercontent.com/106060898/183369449-babd399d-6950-447e-a9e2-b6682a3a52e1.png">

3.NFT Detail Holders
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3747%3A21065
<img width="810" alt="image" src="https://user-images.githubusercontent.com/106060898/183369708-859998c5-245c-4664-bf5c-148c35691ad5.png">

4.NFT Detail Inventory
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3747%3A21239
<img width="851" alt="image" src="https://user-images.githubusercontent.com/106060898/183369938-0b5abdab-ae01-400e-9317-75334a466031.png">

5.NFT Item Detail
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3747%3A21434
<img width="846" alt="image" src="https://user-images.githubusercontent.com/106060898/183370109-9da9deae-56f0-4165-89fb-b53427e38beb.png">

**Comment by Keith-CY** [comment]
No more feedback and design draft confirmed
