### ISSUE TITLE
Add ERC 1155 tokens

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#6]
Text PRD at https://github.com/Magickbase/godwoken_explorer/issues/854#issuecomment-1220169844

BTW, there should an entry to ERC 1155 List in Dropdown-Menu of tokens in the page header, should we add a divider line to separate it from other kind of tokens?

**Comment by Kirl70** [comment]
> Text PRD at [Magickbase/godwoken_explorer#854 (comment)](https://github.com/Magickbase/godwoken_explorer/issues/854#issuecomment-1220169844)
> 
> BTW, there should an entry to ERC 1155 List in Dropdown-Menu of tokens in the page header, should we add a divider line to separate it from other kind of tokens?

Yes, the different types should be separated by a divider line.

**Comment by Keith-CY** [comment]
> > Text PRD at [Magickbase/godwoken_explorer#854 (comment)](https://github.com/Magickbase/godwoken_explorer/issues/854#issuecomment-1220169844)
> > BTW, there should an entry to ERC 1155 List in Dropdown-Menu of tokens in the page header, should we add a divider line to separate it from other kind of tokens?
> 
> Yes, the different types should be separated by line.

👌 please also update it in the design

**Comment by Kirl70** [comment]
Navigation bar drop-down menu:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6%3A2
<img width="416" alt="image" src="https://user-images.githubusercontent.com/106060898/186310977-e738028a-28d7-48bc-b22e-4e0b39bbdfe9.png">

Token Collection List:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4354%3A26697
<img width="830" alt="image" src="https://user-images.githubusercontent.com/106060898/186319417-644653fe-4871-4453-831d-8e666b9b78d8.png">

Token Collection Detail:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4354%3A26371
<img width="851" alt="image" src="https://user-images.githubusercontent.com/106060898/186320497-cd09370b-30c8-45b4-bb3e-557ffcc74851.png">

Token Item Detail:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4354%3A25583
<img width="841" alt="image" src="https://user-images.githubusercontent.com/106060898/186320817-c3c5d2eb-6c75-47a3-a9ca-ab0dbc16aeaa.png">

User's Token Item List:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4354%3A26861
<img width="827" alt="image" src="https://user-images.githubusercontent.com/106060898/186321279-43cf9b3e-06c3-4ede-9a2f-fb5d878435ec.png">

User's Token Activity List:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4354%3A26985
<img width="834" alt="image" src="https://user-images.githubusercontent.com/106060898/186322035-d069fbab-5265-426c-b713-8964f1b83b37.png">
