### ISSUE TITLE
Rebuild design draft of ckb explorer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#7]
We have to rebuild the design draft because the original one is lost.

The best solution is to redesign it from scratch, however, the response from the foundation is that we can build a new one as a new product but the running one should be kept.

So we'd better rebuild the design draft of it for maintenance.

Text PRD has been organized on https://github.com/Magickbase/ckb-explorer-public-issues/pull/73. Any questions could be commented and I'll add more details.

**Comment by Kirl70** [comment]
So the style of the new design needs to be consistent with the current one?

**Comment by Keith-CY** [comment]
> So the style of the new design needs to be consistent with the current one?

We're going to have two design drafts: rebuild the current one and design a new one

At this stage, we'll just rebuild the current one, simply transform the online page into a Figma draft. We will maintain the online pages for several months so PRD(just organized these days) and design draft are necessary.

And we may add a new explorer, which will be designed from scratch, both in functions and styles. It would be future work since we need a new PRD for it. Its style just needs to follow the **CKB Products Visual Guide** mentioned in https://github.com/Magickbase/visual-style-guide

**Comment by Kirl70** [comment]
> > So the style of the new design needs to be consistent with the current one?
> 
> We're going to have two design drafts: rebuild the current one and design a new one
> 
> In this stage, we'll just rebuild the current one, simply transform the online page into a Figma draft. We will maintain the online pages for several months so PRD(just organized these days) and design draft are necessary.
> 
> And we may add a new explorer, which will be designed from scratch, both in functions and styles. It would be future work since we need a new PRD for it. Its style just needs to follow the **CKB Products Visual Guide** mentioned in https://github.com/Magickbase/visual-style-guide

Got it.

**Comment by Keith-CY** [comment]
I've seen the drafts updated in https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3745%3A20658 are they all ready?

**Comment by Kirl70** [comment]
There are still some mobile pages, which will be completed tomorrow

**Comment by Kirl70** [comment]
The current page reconstruction design draft has been completed : https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=3745%3A20658
