### ISSUE TITLE
Add two icons for cota cells

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/visual-style-guide#8]
On the transaction page, some cells are marked with icons, like m-NFT here
https://explorer.nervos.org/transaction/0x814d82167c1266888ab928c7fc57d71da2dc826dd2b0f28e468e73ad06eb16dd
![image](https://user-images.githubusercontent.com/7271329/196619536-10e27a6f-6129-4baf-964e-4a53889d91a8.png)

Now there'll be 2 more cell types, named `CoTA REG` and `CoTA`, `CoTA REG` means a registry and `CoTA` is one member

`CoTA` has its own logo
![cota](https://user-images.githubusercontent.com/7271329/196619884-c1d28592-d74b-4426-81e5-115fa8c1de7f.png)
but is inconsistent with other icons, we'd better re-design two icons based on the CoTA logo following the m-NFT icon style

Other icons:
![udt_token](https://user-images.githubusercontent.com/7271329/196620213-0fa29ead-ca03-40b9-86af-e6730b3c4f1c.png)
![nervos_dao_cell](https://user-images.githubusercontent.com/7271329/196620231-39227b20-76be-4ec4-9e1e-8448ab07d420.png)
![nervos_dao_withdrawing](https://user-images.githubusercontent.com/7271329/196620234-667dcc71-00e6-4512-8b66-788d1ed18098.png)
![m_nft_class](https://user-images.githubusercontent.com/7271329/196620278-0ceef237-623e-48fc-811a-42b028c894c7.svg)
![m_nft_issuer](https://user-images.githubusercontent.com/7271329/196620283-95d59a0c-a3ed-4160-871a-0f9363693827.svg)
![m_nft](https://user-images.githubusercontent.com/7271329/196620284-7ae21e33-9fc4-4f4b-9f6d-c44a7d92274a.svg)

Ref: 
CoTA: https://www.cotadev.io/

**Comment by Kirl70** [comment]
`CoTA` and `CoTA REG` icons

<img width="494" alt="image" src="https://user-images.githubusercontent.com/106060898/196696592-d2ddec9b-e3e1-45a6-b698-5c4a1e504bc6.png">

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5815%3A27130
